// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotfixChatMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ETHotfix {

  #region Messages
  /// <summary>
  /// Opcode = 22000
  /// 请求 进入聊天房间
  /// </summary>
  public partial class C2G_EnterChatRoom : pb::IMessage {
    private static readonly pb::MessageParser<C2G_EnterChatRoom> _parser = new pb::MessageParser<C2G_EnterChatRoom>(() => (C2G_EnterChatRoom)MessagePool.Instance.Fetch(typeof(C2G_EnterChatRoom)));
    public static pb::MessageParser<C2G_EnterChatRoom> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long chatRoomID_;
    public long ChatRoomID {
      get { return chatRoomID_; }
      set {
        chatRoomID_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ChatRoomID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ChatRoomID);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ChatRoomID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChatRoomID);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      chatRoomID_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ChatRoomID = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 进入聊天房间  
  /// </summary>
  public partial class G2C_EnterChatRoom : pb::IMessage {
    private static readonly pb::MessageParser<G2C_EnterChatRoom> _parser = new pb::MessageParser<G2C_EnterChatRoom>(() => (G2C_EnterChatRoom)MessagePool.Instance.Fetch(typeof(G2C_EnterChatRoom)));
    public static pb::MessageParser<G2C_EnterChatRoom> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 离开聊天房间
  /// </summary>
  public partial class C2G_LeaveChatRoom : pb::IMessage {
    private static readonly pb::MessageParser<C2G_LeaveChatRoom> _parser = new pb::MessageParser<C2G_LeaveChatRoom>(() => (C2G_LeaveChatRoom)MessagePool.Instance.Fetch(typeof(C2G_LeaveChatRoom)));
    public static pb::MessageParser<C2G_LeaveChatRoom> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long chatRoomID_;
    public long ChatRoomID {
      get { return chatRoomID_; }
      set {
        chatRoomID_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ChatRoomID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ChatRoomID);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ChatRoomID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChatRoomID);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      chatRoomID_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ChatRoomID = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 离开聊天房间
  /// </summary>
  public partial class G2C_LeaveChatRoom : pb::IMessage {
    private static readonly pb::MessageParser<G2C_LeaveChatRoom> _parser = new pb::MessageParser<G2C_LeaveChatRoom>(() => (G2C_LeaveChatRoom)MessagePool.Instance.Fetch(typeof(G2C_LeaveChatRoom)));
    public static pb::MessageParser<G2C_LeaveChatRoom> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 发送消息到聊天房间
  /// </summary>
  public partial class C2G_SendChatMessageToChatRoom : pb::IMessage {
    private static readonly pb::MessageParser<C2G_SendChatMessageToChatRoom> _parser = new pb::MessageParser<C2G_SendChatMessageToChatRoom>(() => (C2G_SendChatMessageToChatRoom)MessagePool.Instance.Fetch(typeof(C2G_SendChatMessageToChatRoom)));
    public static pb::MessageParser<C2G_SendChatMessageToChatRoom> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long chatRoomID_;
    public long ChatRoomID {
      get { return chatRoomID_; }
      set {
        chatRoomID_ = value;
      }
    }

    private string chatMessage_ = "";
    public string ChatMessage {
      get { return chatMessage_; }
      set {
        chatMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ChatRoomID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ChatRoomID);
      }
      if (ChatMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChatMessage);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ChatRoomID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChatRoomID);
      }
      if (ChatMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMessage);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      chatRoomID_ = 0;
      chatMessage_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ChatRoomID = input.ReadInt64();
            break;
          }
          case 18: {
            ChatMessage = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 发送消息到聊天房间
  /// </summary>
  public partial class G2C_SendChatMessageToChatRoom : pb::IMessage {
    private static readonly pb::MessageParser<G2C_SendChatMessageToChatRoom> _parser = new pb::MessageParser<G2C_SendChatMessageToChatRoom>(() => (G2C_SendChatMessageToChatRoom)MessagePool.Instance.Fetch(typeof(G2C_SendChatMessageToChatRoom)));
    public static pb::MessageParser<G2C_SendChatMessageToChatRoom> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 私聊聊天消息
  /// </summary>
  public partial class C2G_SendChatMessageToPlayer : pb::IMessage {
    private static readonly pb::MessageParser<C2G_SendChatMessageToPlayer> _parser = new pb::MessageParser<C2G_SendChatMessageToPlayer>(() => (C2G_SendChatMessageToPlayer)MessagePool.Instance.Fetch(typeof(C2G_SendChatMessageToPlayer)));
    public static pb::MessageParser<C2G_SendChatMessageToPlayer> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long playerGameUserId_;
    public long PlayerGameUserId {
      get { return playerGameUserId_; }
      set {
        playerGameUserId_ = value;
      }
    }

    private string chatMessage_ = "";
    public string ChatMessage {
      get { return chatMessage_; }
      set {
        chatMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerGameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerGameUserId);
      }
      if (ChatMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChatMessage);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (PlayerGameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerGameUserId);
      }
      if (ChatMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMessage);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      playerGameUserId_ = 0;
      chatMessage_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerGameUserId = input.ReadInt64();
            break;
          }
          case 18: {
            ChatMessage = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 私聊聊天消息
  /// </summary>
  public partial class G2C_SendChatMessageToPlayer : pb::IMessage {
    private static readonly pb::MessageParser<G2C_SendChatMessageToPlayer> _parser = new pb::MessageParser<G2C_SendChatMessageToPlayer>(() => (G2C_SendChatMessageToPlayer)MessagePool.Instance.Fetch(typeof(G2C_SendChatMessageToPlayer)));
    public static pb::MessageParser<G2C_SendChatMessageToPlayer> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 发送消息到附近
  /// </summary>
  public partial class C2G_SendChatMessageToNearby : pb::IMessage {
    private static readonly pb::MessageParser<C2G_SendChatMessageToNearby> _parser = new pb::MessageParser<C2G_SendChatMessageToNearby>(() => (C2G_SendChatMessageToNearby)MessagePool.Instance.Fetch(typeof(C2G_SendChatMessageToNearby)));
    public static pb::MessageParser<C2G_SendChatMessageToNearby> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private string chatMessage_ = "";
    public string ChatMessage {
      get { return chatMessage_; }
      set {
        chatMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ChatMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ChatMessage);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ChatMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMessage);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      chatMessage_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ChatMessage = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 发送消息到附近
  /// </summary>
  public partial class G2C_SendChatMessageToNearby : pb::IMessage {
    private static readonly pb::MessageParser<G2C_SendChatMessageToNearby> _parser = new pb::MessageParser<G2C_SendChatMessageToNearby>(() => (G2C_SendChatMessageToNearby)MessagePool.Instance.Fetch(typeof(G2C_SendChatMessageToNearby)));
    public static pb::MessageParser<G2C_SendChatMessageToNearby> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///通知 消息到达聊天房间
  /// </summary>
  public partial class G2C_MessageInChatRoom_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_MessageInChatRoom_notice> _parser = new pb::MessageParser<G2C_MessageInChatRoom_notice>(() => (G2C_MessageInChatRoom_notice)MessagePool.Instance.Fetch(typeof(G2C_MessageInChatRoom_notice)));
    public static pb::MessageParser<G2C_MessageInChatRoom_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long chatRoomID_;
    /// <summary>
    /// 聊天房间Id
    /// </summary>
    public long ChatRoomID {
      get { return chatRoomID_; }
      set {
        chatRoomID_ = value;
      }
    }

    private long sendGameUserId_;
    /// <summary>
    /// 发送消息的实体GameUserId
    /// </summary>
    public long SendGameUserId {
      get { return sendGameUserId_; }
      set {
        sendGameUserId_ = value;
      }
    }

    private string sendUserName_ = "";
    /// <summary>
    /// 发送消息的实体昵称
    /// </summary>
    public string SendUserName {
      get { return sendUserName_; }
      set {
        sendUserName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long sendTime_;
    /// <summary>
    /// 消息发送时间 时间戳 秒
    /// </summary>
    public long SendTime {
      get { return sendTime_; }
      set {
        sendTime_ = value;
      }
    }

    private string chatMessage_ = "";
    /// <summary>
    /// 聊天消息
    /// </summary>
    public string ChatMessage {
      get { return chatMessage_; }
      set {
        chatMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ChatRoomID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ChatRoomID);
      }
      if (SendGameUserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SendGameUserId);
      }
      if (SendUserName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SendUserName);
      }
      if (SendTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SendTime);
      }
      if (ChatMessage.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ChatMessage);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (ChatRoomID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChatRoomID);
      }
      if (SendGameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendGameUserId);
      }
      if (SendUserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SendUserName);
      }
      if (SendTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendTime);
      }
      if (ChatMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMessage);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      chatRoomID_ = 0;
      sendGameUserId_ = 0;
      sendUserName_ = "";
      sendTime_ = 0;
      chatMessage_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ChatRoomID = input.ReadInt64();
            break;
          }
          case 16: {
            SendGameUserId = input.ReadInt64();
            break;
          }
          case 26: {
            SendUserName = input.ReadString();
            break;
          }
          case 32: {
            SendTime = input.ReadInt64();
            break;
          }
          case 42: {
            ChatMessage = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///通知 收到一条私聊消息
  /// </summary>
  public partial class ReceivePlayerChatMessage_notice : pb::IMessage {
    private static readonly pb::MessageParser<ReceivePlayerChatMessage_notice> _parser = new pb::MessageParser<ReceivePlayerChatMessage_notice>(() => (ReceivePlayerChatMessage_notice)MessagePool.Instance.Fetch(typeof(ReceivePlayerChatMessage_notice)));
    public static pb::MessageParser<ReceivePlayerChatMessage_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long playerGameUserId_;
    /// <summary>
    /// 发送消息的实体GameUserId
    /// </summary>
    public long PlayerGameUserId {
      get { return playerGameUserId_; }
      set {
        playerGameUserId_ = value;
      }
    }

    private string playerName_ = "";
    /// <summary>
    /// 发送消息的实体昵称
    /// </summary>
    public string PlayerName {
      get { return playerName_; }
      set {
        playerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long sendTime_;
    public long SendTime {
      get { return sendTime_; }
      set {
        sendTime_ = value;
      }
    }

    private string chatMessage_ = "";
    public string ChatMessage {
      get { return chatMessage_; }
      set {
        chatMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerGameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerGameUserId);
      }
      if (PlayerName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PlayerName);
      }
      if (SendTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SendTime);
      }
      if (ChatMessage.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ChatMessage);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (PlayerGameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerGameUserId);
      }
      if (PlayerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerName);
      }
      if (SendTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendTime);
      }
      if (ChatMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMessage);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      playerGameUserId_ = 0;
      playerName_ = "";
      sendTime_ = 0;
      chatMessage_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerGameUserId = input.ReadInt64();
            break;
          }
          case 18: {
            PlayerName = input.ReadString();
            break;
          }
          case 24: {
            SendTime = input.ReadInt64();
            break;
          }
          case 34: {
            ChatMessage = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///通知 来自附近的聊天消息
  /// </summary>
  public partial class ChatMessageFromNearby_notice : pb::IMessage {
    private static readonly pb::MessageParser<ChatMessageFromNearby_notice> _parser = new pb::MessageParser<ChatMessageFromNearby_notice>(() => (ChatMessageFromNearby_notice)MessagePool.Instance.Fetch(typeof(ChatMessageFromNearby_notice)));
    public static pb::MessageParser<ChatMessageFromNearby_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long sendGameUserId_;
    /// <summary>
    /// 发送消息的实体GameUserId
    /// </summary>
    public long SendGameUserId {
      get { return sendGameUserId_; }
      set {
        sendGameUserId_ = value;
      }
    }

    private string sendUserName_ = "";
    /// <summary>
    /// 发送消息的实体昵称
    /// </summary>
    public string SendUserName {
      get { return sendUserName_; }
      set {
        sendUserName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long sendTime_;
    public long SendTime {
      get { return sendTime_; }
      set {
        sendTime_ = value;
      }
    }

    private string chatMessage_ = "";
    public string ChatMessage {
      get { return chatMessage_; }
      set {
        chatMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (SendGameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SendGameUserId);
      }
      if (SendUserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SendUserName);
      }
      if (SendTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SendTime);
      }
      if (ChatMessage.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ChatMessage);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (SendGameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendGameUserId);
      }
      if (SendUserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SendUserName);
      }
      if (SendTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendTime);
      }
      if (ChatMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMessage);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      sendGameUserId_ = 0;
      sendUserName_ = "";
      sendTime_ = 0;
      chatMessage_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            SendGameUserId = input.ReadInt64();
            break;
          }
          case 18: {
            SendUserName = input.ReadString();
            break;
          }
          case 24: {
            SendTime = input.ReadInt64();
            break;
          }
          case 34: {
            ChatMessage = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class C2G_FullServiceHornRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_FullServiceHornRequest> _parser = new pb::MessageParser<C2G_FullServiceHornRequest>(() => (C2G_FullServiceHornRequest)MessagePool.Instance.Fetch(typeof(C2G_FullServiceHornRequest)));
    public static pb::MessageParser<C2G_FullServiceHornRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private string chatMessage_ = "";
    public string ChatMessage {
      get { return chatMessage_; }
      set {
        chatMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ChatMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ChatMessage);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ChatMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMessage);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      chatMessage_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ChatMessage = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_FullServiceHornResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_FullServiceHornResponse> _parser = new pb::MessageParser<G2C_FullServiceHornResponse>(() => (G2C_FullServiceHornResponse)MessagePool.Instance.Fetch(typeof(G2C_FullServiceHornResponse)));
    public static pb::MessageParser<G2C_FullServiceHornResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_FullServiceHornnotice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_FullServiceHornnotice> _parser = new pb::MessageParser<G2C_FullServiceHornnotice>(() => (G2C_FullServiceHornnotice)MessagePool.Instance.Fetch(typeof(G2C_FullServiceHornnotice)));
    public static pb::MessageParser<G2C_FullServiceHornnotice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long sendGameUserId_;
    /// <summary>
    /// 发送消息的实体GameUserId
    /// </summary>
    public long SendGameUserId {
      get { return sendGameUserId_; }
      set {
        sendGameUserId_ = value;
      }
    }

    private string sendUserName_ = "";
    /// <summary>
    /// 发送消息的实体昵称
    /// </summary>
    public string SendUserName {
      get { return sendUserName_; }
      set {
        sendUserName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long sendTime_;
    public long SendTime {
      get { return sendTime_; }
      set {
        sendTime_ = value;
      }
    }

    private string messageInfo_ = "";
    public string MessageInfo {
      get { return messageInfo_; }
      set {
        messageInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int lineId_;
    public int LineId {
      get { return lineId_; }
      set {
        lineId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (SendGameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SendGameUserId);
      }
      if (SendUserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SendUserName);
      }
      if (SendTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SendTime);
      }
      if (MessageInfo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MessageInfo);
      }
      if (LineId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(LineId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (SendGameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendGameUserId);
      }
      if (SendUserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SendUserName);
      }
      if (SendTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendTime);
      }
      if (MessageInfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageInfo);
      }
      if (LineId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LineId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      sendGameUserId_ = 0;
      sendUserName_ = "";
      sendTime_ = 0;
      messageInfo_ = "";
      lineId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            SendGameUserId = input.ReadInt64();
            break;
          }
          case 18: {
            SendUserName = input.ReadString();
            break;
          }
          case 24: {
            SendTime = input.ReadInt64();
            break;
          }
          case 34: {
            MessageInfo = input.ReadString();
            break;
          }
          case 40: {
            LineId = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class C2G_BagShareRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_BagShareRequest> _parser = new pb::MessageParser<C2G_BagShareRequest>(() => (C2G_BagShareRequest)MessagePool.Instance.Fetch(typeof(C2G_BagShareRequest)));
    public static pb::MessageParser<C2G_BagShareRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long shareItemId_;
    public long ShareItemId {
      get { return shareItemId_; }
      set {
        shareItemId_ = value;
      }
    }

    private int color_;
    /// <summary>
    ///颜色
    /// </summary>
    public int Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    private string messageInfo_ = "";
    /// <summary>
    ///名字
    /// </summary>
    public string MessageInfo {
      get { return messageInfo_; }
      set {
        messageInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ShareItemId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ShareItemId);
      }
      if (Color != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Color);
      }
      if (MessageInfo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MessageInfo);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ShareItemId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ShareItemId);
      }
      if (Color != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Color);
      }
      if (MessageInfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageInfo);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      shareItemId_ = 0;
      color_ = 0;
      messageInfo_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ShareItemId = input.ReadInt64();
            break;
          }
          case 16: {
            Color = input.ReadInt32();
            break;
          }
          case 26: {
            MessageInfo = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_BagShareResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_BagShareResponse> _parser = new pb::MessageParser<G2C_BagShareResponse>(() => (G2C_BagShareResponse)MessagePool.Instance.Fetch(typeof(G2C_BagShareResponse)));
    public static pb::MessageParser<G2C_BagShareResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
