// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotfixTaskMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ETHotfix {

  #region Messages
  /// <summary>
  /// 任务
  /// </summary>
  public partial class Struct_TaskInfo : pb::IMessage {
    private static readonly pb::MessageParser<Struct_TaskInfo> _parser = new pb::MessageParser<Struct_TaskInfo>(() => (Struct_TaskInfo)MessagePool.Instance.Fetch(typeof(Struct_TaskInfo)));
    public static pb::MessageParser<Struct_TaskInfo> Parser { get { return _parser; } }

    private int id_;
    /// <summary>
    /// 任务配置id  
    /// 任务类型: id / 100000 
    /// </summary>
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    private int state_;
    /// <summary>
    /// 状态
    /// 0.无状态  还没领取的任务，当玩家满足条件时，自动领取
    /// 1.进行中
    /// 2.已完成
    /// 3.已领取
    /// </summary>
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    private static readonly pb::FieldCodec<int> _repeated_progress_codec
        = pb::FieldCodec.ForInt32(26);
    private pbc::RepeatedField<int> progress_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 任务进度
    /// </summary>
    public pbc::RepeatedField<int> Progress {
      get { return progress_; }
      set { progress_ = value; }
    }

    private int startTask_;
    /// <summary>
    /// 0.不是第一次推送
    /// 1.任务刚开始。第一次推给玩家
    /// </summary>
    public int StartTask {
      get { return startTask_; }
      set {
        startTask_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (State != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(State);
      }
      progress_.WriteTo(output, _repeated_progress_codec);
      if (StartTask != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(StartTask);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      size += progress_.CalculateSize(_repeated_progress_codec);
      if (StartTask != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartTask);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      id_ = 0;
      state_ = 0;
      progress_.Clear();
      startTask_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            State = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            progress_.AddEntriesFrom(input, _repeated_progress_codec);
            break;
          }
          case 32: {
            StartTask = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 领取任务
  /// 领取成功，会推送 G2C_UpdateGameTaskNotice
  /// </summary>
  public partial class C2G_ReceiveTask : pb::IMessage {
    private static readonly pb::MessageParser<C2G_ReceiveTask> _parser = new pb::MessageParser<C2G_ReceiveTask>(() => (C2G_ReceiveTask)MessagePool.Instance.Fetch(typeof(C2G_ReceiveTask)));
    public static pb::MessageParser<C2G_ReceiveTask> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int taskId_;
    public int TaskId {
      get { return taskId_; }
      set {
        taskId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (TaskId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      taskId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 领取任务
  /// </summary>
  public partial class G2C_ReceiveTask : pb::IMessage {
    private static readonly pb::MessageParser<G2C_ReceiveTask> _parser = new pb::MessageParser<G2C_ReceiveTask>(() => (G2C_ReceiveTask)MessagePool.Instance.Fetch(typeof(G2C_ReceiveTask)));
    public static pb::MessageParser<G2C_ReceiveTask> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 放弃任务
  /// 放弃成功后，不会推送 任务变动的通知
  /// </summary>
  public partial class C2G_AbandonTask : pb::IMessage {
    private static readonly pb::MessageParser<C2G_AbandonTask> _parser = new pb::MessageParser<C2G_AbandonTask>(() => (C2G_AbandonTask)MessagePool.Instance.Fetch(typeof(C2G_AbandonTask)));
    public static pb::MessageParser<C2G_AbandonTask> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int taskId_;
    public int TaskId {
      get { return taskId_; }
      set {
        taskId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (TaskId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      taskId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 放弃任务
  /// </summary>
  public partial class G2C_AbandonTask : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AbandonTask> _parser = new pb::MessageParser<G2C_AbandonTask>(() => (G2C_AbandonTask)MessagePool.Instance.Fetch(typeof(G2C_AbandonTask)));
    public static pb::MessageParser<G2C_AbandonTask> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 领取任务奖励
  /// 领取任务奖励成功后，会推送 G2C_UpdateGameTaskNotice
  /// </summary>
  public partial class C2G_ReceiveTaskReward : pb::IMessage {
    private static readonly pb::MessageParser<C2G_ReceiveTaskReward> _parser = new pb::MessageParser<C2G_ReceiveTaskReward>(() => (C2G_ReceiveTaskReward)MessagePool.Instance.Fetch(typeof(C2G_ReceiveTaskReward)));
    public static pb::MessageParser<C2G_ReceiveTaskReward> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int taskId_;
    public int TaskId {
      get { return taskId_; }
      set {
        taskId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (TaskId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      taskId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 领取任务奖励
  /// </summary>
  public partial class G2C_ReceiveTaskReward : pb::IMessage {
    private static readonly pb::MessageParser<G2C_ReceiveTaskReward> _parser = new pb::MessageParser<G2C_ReceiveTaskReward>(() => (G2C_ReceiveTaskReward)MessagePool.Instance.Fetch(typeof(G2C_ReceiveTaskReward)));
    public static pb::MessageParser<G2C_ReceiveTaskReward> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 更新任务进度
  /// </summary>
  public partial class C2G_UpdateTaskProgress : pb::IMessage {
    private static readonly pb::MessageParser<C2G_UpdateTaskProgress> _parser = new pb::MessageParser<C2G_UpdateTaskProgress>(() => (C2G_UpdateTaskProgress)MessagePool.Instance.Fetch(typeof(C2G_UpdateTaskProgress)));
    public static pb::MessageParser<C2G_UpdateTaskProgress> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int taskId_;
    public int TaskId {
      get { return taskId_; }
      set {
        taskId_ = value;
      }
    }

    private int progressId_;
    public int ProgressId {
      get { return progressId_; }
      set {
        progressId_ = value;
      }
    }

    private int value_;
    public int Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (ProgressId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ProgressId);
      }
      if (Value != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Value);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (TaskId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskId);
      }
      if (ProgressId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProgressId);
      }
      if (Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      taskId_ = 0;
      progressId_ = 0;
      value_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 16: {
            ProgressId = input.ReadInt32();
            break;
          }
          case 24: {
            Value = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回 更新任务进度
  /// </summary>
  public partial class G2C_UpdateTaskProgress : pb::IMessage {
    private static readonly pb::MessageParser<G2C_UpdateTaskProgress> _parser = new pb::MessageParser<G2C_UpdateTaskProgress>(() => (G2C_UpdateTaskProgress)MessagePool.Instance.Fetch(typeof(G2C_UpdateTaskProgress)));
    public static pb::MessageParser<G2C_UpdateTaskProgress> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// ================== 通知 =========================
  /// Opcode = 36500
  /// 通知 更新任务
  /// 领取任务、任务进度变动、任务完成、领取奖励 都会推送
  /// </summary>
  public partial class G2C_UpdateGameTaskNotice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_UpdateGameTaskNotice> _parser = new pb::MessageParser<G2C_UpdateGameTaskNotice>(() => (G2C_UpdateGameTaskNotice)MessagePool.Instance.Fetch(typeof(G2C_UpdateGameTaskNotice)));
    public static pb::MessageParser<G2C_UpdateGameTaskNotice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private global::ETHotfix.Struct_TaskInfo taskInfo_;
    public global::ETHotfix.Struct_TaskInfo TaskInfo {
      get { return taskInfo_; }
      set {
        taskInfo_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (taskInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TaskInfo);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (taskInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TaskInfo);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      if (taskInfo_ != null) MessagePool.Instance.Recycle(taskInfo_); taskInfo_ = null;
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (taskInfo_ == null) {
              taskInfo_ = new global::ETHotfix.Struct_TaskInfo();
            }
            input.ReadMessage(taskInfo_);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 通知 更新全部任务
  /// 进入游戏时通知
  /// </summary>
  public partial class G2C_AllUpdateGameTaskNotice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AllUpdateGameTaskNotice> _parser = new pb::MessageParser<G2C_AllUpdateGameTaskNotice>(() => (G2C_AllUpdateGameTaskNotice)MessagePool.Instance.Fetch(typeof(G2C_AllUpdateGameTaskNotice)));
    public static pb::MessageParser<G2C_AllUpdateGameTaskNotice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_TaskInfo> _repeated_mainTasks_codec
        = pb::FieldCodec.ForMessage(10, global::ETHotfix.Struct_TaskInfo.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> mainTasks_ = new pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo>();
    /// <summary>
    /// 主线任务
    /// </summary>
    public pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> MainTasks {
      get { return mainTasks_; }
      set { mainTasks_ = value; }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_TaskInfo> _repeated_huntingTasks_codec
        = pb::FieldCodec.ForMessage(18, global::ETHotfix.Struct_TaskInfo.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> huntingTasks_ = new pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo>();
    /// <summary>
    /// 狩猎任务
    /// </summary>
    public pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> HuntingTasks {
      get { return huntingTasks_; }
      set { huntingTasks_ = value; }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_TaskInfo> _repeated_activityTasks_codec
        = pb::FieldCodec.ForMessage(26, global::ETHotfix.Struct_TaskInfo.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> activityTasks_ = new pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo>();
    /// <summary>
    /// 活动任务
    /// </summary>
    public pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> ActivityTasks {
      get { return activityTasks_; }
      set { activityTasks_ = value; }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_TaskInfo> _repeated_entrustTasks_codec
        = pb::FieldCodec.ForMessage(34, global::ETHotfix.Struct_TaskInfo.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> entrustTasks_ = new pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo>();
    /// <summary>
    /// 委托任务
    /// </summary>
    public pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> EntrustTasks {
      get { return entrustTasks_; }
      set { entrustTasks_ = value; }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_TaskInfo> _repeated_careerChangeTasks_codec
        = pb::FieldCodec.ForMessage(42, global::ETHotfix.Struct_TaskInfo.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> careerChangeTasks_ = new pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo>();
    /// <summary>
    /// 转职任务
    /// </summary>
    public pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> CareerChangeTasks {
      get { return careerChangeTasks_; }
      set { careerChangeTasks_ = value; }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_TaskInfo> _repeated_passTasks_codec
        = pb::FieldCodec.ForMessage(50, global::ETHotfix.Struct_TaskInfo.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> passTasks_ = new pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo>();
    /// <summary>
    /// 通行证任务
    /// </summary>
    public pbc::RepeatedField<global::ETHotfix.Struct_TaskInfo> PassTasks {
      get { return passTasks_; }
      set { passTasks_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      mainTasks_.WriteTo(output, _repeated_mainTasks_codec);
      huntingTasks_.WriteTo(output, _repeated_huntingTasks_codec);
      activityTasks_.WriteTo(output, _repeated_activityTasks_codec);
      entrustTasks_.WriteTo(output, _repeated_entrustTasks_codec);
      careerChangeTasks_.WriteTo(output, _repeated_careerChangeTasks_codec);
      passTasks_.WriteTo(output, _repeated_passTasks_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      size += mainTasks_.CalculateSize(_repeated_mainTasks_codec);
      size += huntingTasks_.CalculateSize(_repeated_huntingTasks_codec);
      size += activityTasks_.CalculateSize(_repeated_activityTasks_codec);
      size += entrustTasks_.CalculateSize(_repeated_entrustTasks_codec);
      size += careerChangeTasks_.CalculateSize(_repeated_careerChangeTasks_codec);
      size += passTasks_.CalculateSize(_repeated_passTasks_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      for (int i = 0; i < mainTasks_.Count; i++) { MessagePool.Instance.Recycle(mainTasks_[i]); }
      mainTasks_.Clear();
      for (int i = 0; i < huntingTasks_.Count; i++) { MessagePool.Instance.Recycle(huntingTasks_[i]); }
      huntingTasks_.Clear();
      for (int i = 0; i < activityTasks_.Count; i++) { MessagePool.Instance.Recycle(activityTasks_[i]); }
      activityTasks_.Clear();
      for (int i = 0; i < entrustTasks_.Count; i++) { MessagePool.Instance.Recycle(entrustTasks_[i]); }
      entrustTasks_.Clear();
      for (int i = 0; i < careerChangeTasks_.Count; i++) { MessagePool.Instance.Recycle(careerChangeTasks_[i]); }
      careerChangeTasks_.Clear();
      for (int i = 0; i < passTasks_.Count; i++) { MessagePool.Instance.Recycle(passTasks_[i]); }
      passTasks_.Clear();
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            mainTasks_.AddEntriesFrom(input, _repeated_mainTasks_codec);
            break;
          }
          case 18: {
            huntingTasks_.AddEntriesFrom(input, _repeated_huntingTasks_codec);
            break;
          }
          case 26: {
            activityTasks_.AddEntriesFrom(input, _repeated_activityTasks_codec);
            break;
          }
          case 34: {
            entrustTasks_.AddEntriesFrom(input, _repeated_entrustTasks_codec);
            break;
          }
          case 42: {
            careerChangeTasks_.AddEntriesFrom(input, _repeated_careerChangeTasks_codec);
            break;
          }
          case 50: {
            passTasks_.AddEntriesFrom(input, _repeated_passTasks_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 获取新手引导状态
  /// </summary>
  public partial class C2G_GetBeginnerGuideStatus : pb::IMessage {
    private static readonly pb::MessageParser<C2G_GetBeginnerGuideStatus> _parser = new pb::MessageParser<C2G_GetBeginnerGuideStatus>(() => (C2G_GetBeginnerGuideStatus)MessagePool.Instance.Fetch(typeof(C2G_GetBeginnerGuideStatus)));
    public static pb::MessageParser<C2G_GetBeginnerGuideStatus> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_GetBeginnerGuideStatus : pb::IMessage {
    private static readonly pb::MessageParser<G2C_GetBeginnerGuideStatus> _parser = new pb::MessageParser<G2C_GetBeginnerGuideStatus>(() => (G2C_GetBeginnerGuideStatus)MessagePool.Instance.Fetch(typeof(G2C_GetBeginnerGuideStatus)));
    public static pb::MessageParser<G2C_GetBeginnerGuideStatus> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long value_;
    /// <summary>
    /// 状态
    /// </summary>
    public long Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Value != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Value);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      value_ = 0;
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Value = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求 设置新手引导状态
  /// </summary>
  public partial class C2G_SetBeginnerGuideStatus : pb::IMessage {
    private static readonly pb::MessageParser<C2G_SetBeginnerGuideStatus> _parser = new pb::MessageParser<C2G_SetBeginnerGuideStatus>(() => (C2G_SetBeginnerGuideStatus)MessagePool.Instance.Fetch(typeof(C2G_SetBeginnerGuideStatus)));
    public static pb::MessageParser<C2G_SetBeginnerGuideStatus> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long value_;
    /// <summary>
    /// 状态
    /// </summary>
    public long Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Value != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Value);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      value_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Value = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_SetBeginnerGuideStatus : pb::IMessage {
    private static readonly pb::MessageParser<G2C_SetBeginnerGuideStatus> _parser = new pb::MessageParser<G2C_SetBeginnerGuideStatus>(() => (G2C_SetBeginnerGuideStatus)MessagePool.Instance.Fetch(typeof(G2C_SetBeginnerGuideStatus)));
    public static pb::MessageParser<G2C_SetBeginnerGuideStatus> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public partial class C2G_PurchaseOfTradeCard : pb::IMessage {
    private static readonly pb::MessageParser<C2G_PurchaseOfTradeCard> _parser = new pb::MessageParser<C2G_PurchaseOfTradeCard>(() => (C2G_PurchaseOfTradeCard)MessagePool.Instance.Fetch(typeof(C2G_PurchaseOfTradeCard)));
    public static pb::MessageParser<C2G_PurchaseOfTradeCard> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int passId_;
    public int PassId {
      get { return passId_; }
      set {
        passId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (PassId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PassId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (PassId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PassId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      passId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PassId = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_PurchaseOfTradeCard : pb::IMessage {
    private static readonly pb::MessageParser<G2C_PurchaseOfTradeCard> _parser = new pb::MessageParser<G2C_PurchaseOfTradeCard>(() => (G2C_PurchaseOfTradeCard)MessagePool.Instance.Fetch(typeof(G2C_PurchaseOfTradeCard)));
    public static pb::MessageParser<G2C_PurchaseOfTradeCard> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public partial class C2G_ReincarnateRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_ReincarnateRequest> _parser = new pb::MessageParser<C2G_ReincarnateRequest>(() => (C2G_ReincarnateRequest)MessagePool.Instance.Fetch(typeof(C2G_ReincarnateRequest)));
    public static pb::MessageParser<C2G_ReincarnateRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_ReincarnateResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_ReincarnateResponse> _parser = new pb::MessageParser<G2C_ReincarnateResponse>(() => (G2C_ReincarnateResponse)MessagePool.Instance.Fetch(typeof(G2C_ReincarnateResponse)));
    public static pb::MessageParser<G2C_ReincarnateResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int reincarnateCnt_;
    public int ReincarnateCnt {
      get { return reincarnateCnt_; }
      set {
        reincarnateCnt_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ReincarnateCnt != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ReincarnateCnt);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (ReincarnateCnt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReincarnateCnt);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      reincarnateCnt_ = 0;
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ReincarnateCnt = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
