// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotfxMiracleActivitiesMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ETHotfix {

  #region Messages
  /// <summary>
  /// Opcode = 39000
  ///获取相应活动的数据
  /// </summary>
  public partial class C2G_OpenMiracleActivitiesRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_OpenMiracleActivitiesRequest> _parser = new pb::MessageParser<C2G_OpenMiracleActivitiesRequest>(() => (C2G_OpenMiracleActivitiesRequest)MessagePool.Instance.Fetch(typeof(C2G_OpenMiracleActivitiesRequest)));
    public static pb::MessageParser<C2G_OpenMiracleActivitiesRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int miracleActivitiesID_;
    /// <summary>
    ///活动ID
    /// </summary>
    public int MiracleActivitiesID {
      get { return miracleActivitiesID_; }
      set {
        miracleActivitiesID_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (MiracleActivitiesID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MiracleActivitiesID);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (MiracleActivitiesID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MiracleActivitiesID);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      miracleActivitiesID_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MiracleActivitiesID = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///获取相应活动的数据 返回
  /// </summary>
  public partial class G2C_OpenMiracleActivitiesResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_OpenMiracleActivitiesResponse> _parser = new pb::MessageParser<G2C_OpenMiracleActivitiesResponse>(() => (G2C_OpenMiracleActivitiesResponse)MessagePool.Instance.Fetch(typeof(G2C_OpenMiracleActivitiesResponse)));
    public static pb::MessageParser<G2C_OpenMiracleActivitiesResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private global::ETHotfix.struct_MiracleActivities info_;
    /// <summary>
    ///活动数据
    /// </summary>
    public global::ETHotfix.struct_MiracleActivities Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      if (info_ != null) MessagePool.Instance.Recycle(info_); info_ = null;
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (info_ == null) {
              info_ = new global::ETHotfix.struct_MiracleActivities();
            }
            input.ReadMessage(info_);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///冲级活动领奖
  /// </summary>
  public partial class C2G_RushGradeActivityReceiveRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_RushGradeActivityReceiveRequest> _parser = new pb::MessageParser<C2G_RushGradeActivityReceiveRequest>(() => (C2G_RushGradeActivityReceiveRequest)MessagePool.Instance.Fetch(typeof(C2G_RushGradeActivityReceiveRequest)));
    public static pb::MessageParser<C2G_RushGradeActivityReceiveRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int miracleActivitiesID_;
    /// <summary>
    ///活动ID
    /// </summary>
    public int MiracleActivitiesID {
      get { return miracleActivitiesID_; }
      set {
        miracleActivitiesID_ = value;
      }
    }

    private static readonly pb::FieldCodec<int> _repeated_rewardID_codec
        = pb::FieldCodec.ForInt32(18);
    private pbc::RepeatedField<int> rewardID_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///奖励ID
    /// </summary>
    public pbc::RepeatedField<int> RewardID {
      get { return rewardID_; }
      set { rewardID_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (MiracleActivitiesID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MiracleActivitiesID);
      }
      rewardID_.WriteTo(output, _repeated_rewardID_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (MiracleActivitiesID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MiracleActivitiesID);
      }
      size += rewardID_.CalculateSize(_repeated_rewardID_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      miracleActivitiesID_ = 0;
      rewardID_.Clear();
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MiracleActivitiesID = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            rewardID_.AddEntriesFrom(input, _repeated_rewardID_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///冲级活动领奖 返回
  /// </summary>
  public partial class G2C_RushGradeActivityReceiveResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_RushGradeActivityReceiveResponse> _parser = new pb::MessageParser<G2C_RushGradeActivityReceiveResponse>(() => (G2C_RushGradeActivityReceiveResponse)MessagePool.Instance.Fetch(typeof(G2C_RushGradeActivityReceiveResponse)));
    public static pb::MessageParser<G2C_RushGradeActivityReceiveResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private global::ETHotfix.struct_MiracleActivities info_;
    /// <summary>
    ///活动数据
    /// </summary>
    public global::ETHotfix.struct_MiracleActivities Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      if (info_ != null) MessagePool.Instance.Recycle(info_); info_ = null;
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (info_ == null) {
              info_ = new global::ETHotfix.struct_MiracleActivities();
            }
            input.ReadMessage(info_);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///攻城战通知	
  /// </summary>
  public partial class G2C_SendPointOutMessage : pb::IMessage {
    private static readonly pb::MessageParser<G2C_SendPointOutMessage> _parser = new pb::MessageParser<G2C_SendPointOutMessage>(() => (G2C_SendPointOutMessage)MessagePool.Instance.Fetch(typeof(G2C_SendPointOutMessage)));
    public static pb::MessageParser<G2C_SendPointOutMessage> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private int pointout_;
    public int Pointout {
      get { return pointout_; }
      set {
        pointout_ = value;
      }
    }

    private long time_;
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    private int titleName_;
    /// <summary>
    ///称号ID
    /// </summary>
    public int TitleName {
      get { return titleName_; }
      set {
        titleName_ = value;
      }
    }

    private string playerName_ = "";
    public string PlayerName {
      get { return playerName_; }
      set {
        playerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string warName_ = "";
    public string WarName {
      get { return warName_; }
      set {
        warName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int status_;
    public int Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    private long playerId_;
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Pointout != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Pointout);
      }
      if (Time != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Time);
      }
      if (TitleName != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TitleName);
      }
      if (PlayerName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PlayerName);
      }
      if (WarName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(WarName);
      }
      if (Status != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Status);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(PlayerId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (Pointout != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pointout);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (TitleName != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TitleName);
      }
      if (PlayerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerName);
      }
      if (WarName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WarName);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      pointout_ = 0;
      time_ = 0;
      titleName_ = 0;
      playerName_ = "";
      warName_ = "";
      status_ = 0;
      playerId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Pointout = input.ReadInt32();
            break;
          }
          case 16: {
            Time = input.ReadInt64();
            break;
          }
          case 24: {
            TitleName = input.ReadInt32();
            break;
          }
          case 34: {
            PlayerName = input.ReadString();
            break;
          }
          case 42: {
            WarName = input.ReadString();
            break;
          }
          case 48: {
            Status = input.ReadInt32();
            break;
          }
          case 56: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///座上城主位
  /// </summary>
  public partial class C2G_TakeAThroneRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_TakeAThroneRequest> _parser = new pb::MessageParser<C2G_TakeAThroneRequest>(() => (C2G_TakeAThroneRequest)MessagePool.Instance.Fetch(typeof(C2G_TakeAThroneRequest)));
    public static pb::MessageParser<C2G_TakeAThroneRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///座上城主位 返回
  /// </summary>
  public partial class G2C_TakeAThroneResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_TakeAThroneResponse> _parser = new pb::MessageParser<G2C_TakeAThroneResponse>(() => (G2C_TakeAThroneResponse)MessagePool.Instance.Fetch(typeof(G2C_TakeAThroneResponse)));
    public static pb::MessageParser<G2C_TakeAThroneResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///离开座位
  /// </summary>
  public partial class C2G_LeaveYourSeatRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_LeaveYourSeatRequest> _parser = new pb::MessageParser<C2G_LeaveYourSeatRequest>(() => (C2G_LeaveYourSeatRequest)MessagePool.Instance.Fetch(typeof(C2G_LeaveYourSeatRequest)));
    public static pb::MessageParser<C2G_LeaveYourSeatRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///离开座位 返回
  /// </summary>
  public partial class G2C_LeaveYourSeatResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_LeaveYourSeatResponse> _parser = new pb::MessageParser<G2C_LeaveYourSeatResponse>(() => (G2C_LeaveYourSeatResponse)MessagePool.Instance.Fetch(typeof(G2C_LeaveYourSeatResponse)));
    public static pb::MessageParser<G2C_LeaveYourSeatResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///怪物数量
  /// </summary>
  public partial class C2G_NewYearMobCntRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_NewYearMobCntRequest> _parser = new pb::MessageParser<C2G_NewYearMobCntRequest>(() => (C2G_NewYearMobCntRequest)MessagePool.Instance.Fetch(typeof(C2G_NewYearMobCntRequest)));
    public static pb::MessageParser<C2G_NewYearMobCntRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///怪物数量 返回
  /// </summary>
  public partial class G2C_NewYearMobCntResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_NewYearMobCntResponse> _parser = new pb::MessageParser<G2C_NewYearMobCntResponse>(() => (G2C_NewYearMobCntResponse)MessagePool.Instance.Fetch(typeof(G2C_NewYearMobCntResponse)));
    public static pb::MessageParser<G2C_NewYearMobCntResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_MobCnt> _repeated_mobCnt_codec
        = pb::FieldCodec.ForMessage(10, global::ETHotfix.Struct_MobCnt.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_MobCnt> mobCnt_ = new pbc::RepeatedField<global::ETHotfix.Struct_MobCnt>();
    public pbc::RepeatedField<global::ETHotfix.Struct_MobCnt> MobCnt {
      get { return mobCnt_; }
      set { mobCnt_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      mobCnt_.WriteTo(output, _repeated_mobCnt_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      size += mobCnt_.CalculateSize(_repeated_mobCnt_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      for (int i = 0; i < mobCnt_.Count; i++) { MessagePool.Instance.Recycle(mobCnt_[i]); }
      mobCnt_.Clear();
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            mobCnt_.AddEntriesFrom(input, _repeated_mobCnt_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public partial class struct_MiracleActivities : pb::IMessage {
    private static readonly pb::MessageParser<struct_MiracleActivities> _parser = new pb::MessageParser<struct_MiracleActivities>(() => (struct_MiracleActivities)MessagePool.Instance.Fetch(typeof(struct_MiracleActivities)));
    public static pb::MessageParser<struct_MiracleActivities> Parser { get { return _parser; } }

    private int iD_;
    /// <summary>
    ///活动ID
    /// </summary>
    public int ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    private int status_;
    /// <summary>
    ///领奖状态
    /// </summary>
    public int Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    private int value32A_;
    public int Value32A {
      get { return value32A_; }
      set {
        value32A_ = value;
      }
    }

    private int value32B_;
    public int Value32B {
      get { return value32B_; }
      set {
        value32B_ = value;
      }
    }

    private long value64A_;
    public long Value64A {
      get { return value64A_; }
      set {
        value64A_ = value;
      }
    }

    private long value64B_;
    public long Value64B {
      get { return value64B_; }
      set {
        value64B_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ID);
      }
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Status);
      }
      if (Value32A != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Value32A);
      }
      if (Value32B != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Value32B);
      }
      if (Value64A != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Value64A);
      }
      if (Value64B != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Value64B);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      if (Value32A != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32A);
      }
      if (Value32B != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32B);
      }
      if (Value64A != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64A);
      }
      if (Value64B != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64B);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      iD_ = 0;
      status_ = 0;
      value32A_ = 0;
      value32B_ = 0;
      value64A_ = 0;
      value64B_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ID = input.ReadInt32();
            break;
          }
          case 16: {
            Status = input.ReadInt32();
            break;
          }
          case 24: {
            Value32A = input.ReadInt32();
            break;
          }
          case 32: {
            Value32B = input.ReadInt32();
            break;
          }
          case 40: {
            Value64A = input.ReadInt64();
            break;
          }
          case 48: {
            Value64B = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class Struct_MobCnt : pb::IMessage {
    private static readonly pb::MessageParser<Struct_MobCnt> _parser = new pb::MessageParser<Struct_MobCnt>(() => (Struct_MobCnt)MessagePool.Instance.Fetch(typeof(Struct_MobCnt)));
    public static pb::MessageParser<Struct_MobCnt> Parser { get { return _parser; } }

    private int mapID_;
    public int MapID {
      get { return mapID_; }
      set {
        mapID_ = value;
      }
    }

    private int mobCnt_;
    public int MobCnt {
      get { return mobCnt_; }
      set {
        mobCnt_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (MapID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MapID);
      }
      if (MobCnt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MobCnt);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (MapID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MapID);
      }
      if (MobCnt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MobCnt);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      mapID_ = 0;
      mobCnt_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MapID = input.ReadInt32();
            break;
          }
          case 16: {
            MobCnt = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///签到
  /// </summary>
  public partial class C2G_NationalDaySignin : pb::IMessage {
    private static readonly pb::MessageParser<C2G_NationalDaySignin> _parser = new pb::MessageParser<C2G_NationalDaySignin>(() => (C2G_NationalDaySignin)MessagePool.Instance.Fetch(typeof(C2G_NationalDaySignin)));
    public static pb::MessageParser<C2G_NationalDaySignin> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_NationalDaySignin : pb::IMessage {
    private static readonly pb::MessageParser<G2C_NationalDaySignin> _parser = new pb::MessageParser<G2C_NationalDaySignin>(() => (G2C_NationalDaySignin)MessagePool.Instance.Fetch(typeof(G2C_NationalDaySignin)));
    public static pb::MessageParser<G2C_NationalDaySignin> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///打开推广界面
  /// </summary>
  public partial class C2G_OpenInvitationInterface : pb::IMessage {
    private static readonly pb::MessageParser<C2G_OpenInvitationInterface> _parser = new pb::MessageParser<C2G_OpenInvitationInterface>(() => (C2G_OpenInvitationInterface)MessagePool.Instance.Fetch(typeof(C2G_OpenInvitationInterface)));
    public static pb::MessageParser<C2G_OpenInvitationInterface> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_OpenInvitationInterface : pb::IMessage {
    private static readonly pb::MessageParser<G2C_OpenInvitationInterface> _parser = new pb::MessageParser<G2C_OpenInvitationInterface>(() => (G2C_OpenInvitationInterface)MessagePool.Instance.Fetch(typeof(G2C_OpenInvitationInterface)));
    public static pb::MessageParser<G2C_OpenInvitationInterface> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private global::ETHotfix.InvitationInfo info_;
    public global::ETHotfix.InvitationInfo Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      if (info_ != null) MessagePool.Instance.Recycle(info_); info_ = null;
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (info_ == null) {
              info_ = new global::ETHotfix.InvitationInfo();
            }
            input.ReadMessage(info_);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public partial class C2G_PromotionAward : pb::IMessage {
    private static readonly pb::MessageParser<C2G_PromotionAward> _parser = new pb::MessageParser<C2G_PromotionAward>(() => (C2G_PromotionAward)MessagePool.Instance.Fetch(typeof(C2G_PromotionAward)));
    public static pb::MessageParser<C2G_PromotionAward> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int type_;
    /// <summary>
    ///1:领取人数2:领取等级120级3:领取等级220级
    /// </summary>
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Type);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      type_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Type = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_PromotionAward : pb::IMessage {
    private static readonly pb::MessageParser<G2C_PromotionAward> _parser = new pb::MessageParser<G2C_PromotionAward>(() => (G2C_PromotionAward)MessagePool.Instance.Fetch(typeof(G2C_PromotionAward)));
    public static pb::MessageParser<G2C_PromotionAward> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public partial class InvitationInfo : pb::IMessage {
    private static readonly pb::MessageParser<InvitationInfo> _parser = new pb::MessageParser<InvitationInfo>(() => (InvitationInfo)MessagePool.Instance.Fetch(typeof(InvitationInfo)));
    public static pb::MessageParser<InvitationInfo> Parser { get { return _parser; } }

    private string invitationCode_ = "";
    public string InvitationCode {
      get { return invitationCode_; }
      set {
        invitationCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int numberCntI_;
    /// <summary>
    ///邀请的人数
    /// </summary>
    public int NumberCntI {
      get { return numberCntI_; }
      set {
        numberCntI_ = value;
      }
    }

    private int awardStatusI_;
    /// <summary>
    ///邀请的人数领奖状态
    /// </summary>
    public int AwardStatusI {
      get { return awardStatusI_; }
      set {
        awardStatusI_ = value;
      }
    }

    private int numberCntII_;
    /// <summary>
    ///到达120级的人数
    /// </summary>
    public int NumberCntII {
      get { return numberCntII_; }
      set {
        numberCntII_ = value;
      }
    }

    private int awardStatusII_;
    /// <summary>
    ///到达120级的人数领奖状态
    /// </summary>
    public int AwardStatusII {
      get { return awardStatusII_; }
      set {
        awardStatusII_ = value;
      }
    }

    private int numberCntIII_;
    /// <summary>
    ///到达220级的人数
    /// </summary>
    public int NumberCntIII {
      get { return numberCntIII_; }
      set {
        numberCntIII_ = value;
      }
    }

    private int awardStatusIII_;
    /// <summary>
    ///到达220级的人数数领奖状态
    /// </summary>
    public int AwardStatusIII {
      get { return awardStatusIII_; }
      set {
        awardStatusIII_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (InvitationCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InvitationCode);
      }
      if (NumberCntI != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumberCntI);
      }
      if (AwardStatusI != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AwardStatusI);
      }
      if (NumberCntII != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumberCntII);
      }
      if (AwardStatusII != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AwardStatusII);
      }
      if (NumberCntIII != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NumberCntIII);
      }
      if (AwardStatusIII != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(AwardStatusIII);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (InvitationCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InvitationCode);
      }
      if (NumberCntI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberCntI);
      }
      if (AwardStatusI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AwardStatusI);
      }
      if (NumberCntII != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberCntII);
      }
      if (AwardStatusII != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AwardStatusII);
      }
      if (NumberCntIII != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberCntIII);
      }
      if (AwardStatusIII != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AwardStatusIII);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      invitationCode_ = "";
      numberCntI_ = 0;
      awardStatusI_ = 0;
      numberCntII_ = 0;
      awardStatusII_ = 0;
      numberCntIII_ = 0;
      awardStatusIII_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            InvitationCode = input.ReadString();
            break;
          }
          case 16: {
            NumberCntI = input.ReadInt32();
            break;
          }
          case 24: {
            AwardStatusI = input.ReadInt32();
            break;
          }
          case 32: {
            NumberCntII = input.ReadInt32();
            break;
          }
          case 40: {
            AwardStatusII = input.ReadInt32();
            break;
          }
          case 48: {
            NumberCntIII = input.ReadInt32();
            break;
          }
          case 56: {
            AwardStatusIII = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///五一抽奖
  /// </summary>
  public partial class C2G_MayDayLuckyDraw : pb::IMessage {
    private static readonly pb::MessageParser<C2G_MayDayLuckyDraw> _parser = new pb::MessageParser<C2G_MayDayLuckyDraw>(() => (C2G_MayDayLuckyDraw)MessagePool.Instance.Fetch(typeof(C2G_MayDayLuckyDraw)));
    public static pb::MessageParser<C2G_MayDayLuckyDraw> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_MayDayLuckyDraw : pb::IMessage {
    private static readonly pb::MessageParser<G2C_MayDayLuckyDraw> _parser = new pb::MessageParser<G2C_MayDayLuckyDraw>(() => (G2C_MayDayLuckyDraw)MessagePool.Instance.Fetch(typeof(G2C_MayDayLuckyDraw)));
    public static pb::MessageParser<G2C_MayDayLuckyDraw> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int config_;
    public int Config {
      get { return config_; }
      set {
        config_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Config != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Config);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Config != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Config);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      config_ = 0;
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Config = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
