// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerTitleMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ETHotfix {

  #region Messages
  /// <summary>
  /// Opcode = 42000
  ///称号通知
  /// </summary>
  public partial class G2C_ServerSendTitleMessage : pb::IMessage {
    private static readonly pb::MessageParser<G2C_ServerSendTitleMessage> _parser = new pb::MessageParser<G2C_ServerSendTitleMessage>(() => (G2C_ServerSendTitleMessage)MessagePool.Instance.Fetch(typeof(G2C_ServerSendTitleMessage)));
    public static pb::MessageParser<G2C_ServerSendTitleMessage> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private int useTitle_;
    public int UseTitle {
      get { return useTitle_; }
      set {
        useTitle_ = value;
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Title_Status> _repeated_titleList_codec
        = pb::FieldCodec.ForMessage(18, global::ETHotfix.Title_Status.Parser);
    private pbc::RepeatedField<global::ETHotfix.Title_Status> titleList_ = new pbc::RepeatedField<global::ETHotfix.Title_Status>();
    public pbc::RepeatedField<global::ETHotfix.Title_Status> TitleList {
      get { return titleList_; }
      set { titleList_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (UseTitle != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UseTitle);
      }
      titleList_.WriteTo(output, _repeated_titleList_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (UseTitle != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UseTitle);
      }
      size += titleList_.CalculateSize(_repeated_titleList_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      useTitle_ = 0;
      for (int i = 0; i < titleList_.Count; i++) { MessagePool.Instance.Recycle(titleList_[i]); }
      titleList_.Clear();
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UseTitle = input.ReadInt32();
            break;
          }
          case 18: {
            titleList_.AddEntriesFrom(input, _repeated_titleList_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///称号修改
  /// </summary>
  public partial class C2G_SetPlayerTitleRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_SetPlayerTitleRequest> _parser = new pb::MessageParser<C2G_SetPlayerTitleRequest>(() => (C2G_SetPlayerTitleRequest)MessagePool.Instance.Fetch(typeof(C2G_SetPlayerTitleRequest)));
    public static pb::MessageParser<C2G_SetPlayerTitleRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int useTitle_;
    public int UseTitle {
      get { return useTitle_; }
      set {
        useTitle_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (UseTitle != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UseTitle);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (UseTitle != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UseTitle);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      useTitle_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UseTitle = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_SetPlayerTitleResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_SetPlayerTitleResponse> _parser = new pb::MessageParser<G2C_SetPlayerTitleResponse>(() => (G2C_SetPlayerTitleResponse)MessagePool.Instance.Fetch(typeof(G2C_SetPlayerTitleResponse)));
    public static pb::MessageParser<G2C_SetPlayerTitleResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///称号删除
  /// </summary>
  public partial class C2G_DelPlayerTitleRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_DelPlayerTitleRequest> _parser = new pb::MessageParser<C2G_DelPlayerTitleRequest>(() => (C2G_DelPlayerTitleRequest)MessagePool.Instance.Fetch(typeof(C2G_DelPlayerTitleRequest)));
    public static pb::MessageParser<C2G_DelPlayerTitleRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int useTitle_;
    public int UseTitle {
      get { return useTitle_; }
      set {
        useTitle_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (UseTitle != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UseTitle);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (UseTitle != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UseTitle);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      useTitle_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UseTitle = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_DelPlayerTitleResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_DelPlayerTitleResponse> _parser = new pb::MessageParser<G2C_DelPlayerTitleResponse>(() => (G2C_DelPlayerTitleResponse)MessagePool.Instance.Fetch(typeof(G2C_DelPlayerTitleResponse)));
    public static pb::MessageParser<G2C_DelPlayerTitleResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///获取排行
  /// </summary>
  public partial class C2G_GetRankInfoRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_GetRankInfoRequest> _parser = new pb::MessageParser<C2G_GetRankInfoRequest>(() => (C2G_GetRankInfoRequest)MessagePool.Instance.Fetch(typeof(C2G_GetRankInfoRequest)));
    public static pb::MessageParser<C2G_GetRankInfoRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int rankType_;
    public int RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RankType);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RankType);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rankType_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            RankType = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_GetRankInfoResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_GetRankInfoResponse> _parser = new pb::MessageParser<G2C_GetRankInfoResponse>(() => (G2C_GetRankInfoResponse)MessagePool.Instance.Fetch(typeof(G2C_GetRankInfoResponse)));
    public static pb::MessageParser<G2C_GetRankInfoResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long gameUserID_;
    public long GameUserID {
      get { return gameUserID_; }
      set {
        gameUserID_ = value;
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Rank_status> _repeated_rankList_codec
        = pb::FieldCodec.ForMessage(18, global::ETHotfix.Rank_status.Parser);
    private pbc::RepeatedField<global::ETHotfix.Rank_status> rankList_ = new pbc::RepeatedField<global::ETHotfix.Rank_status>();
    public pbc::RepeatedField<global::ETHotfix.Rank_status> RankList {
      get { return rankList_; }
      set { rankList_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserID);
      }
      rankList_.WriteTo(output, _repeated_rankList_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (GameUserID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserID);
      }
      size += rankList_.CalculateSize(_repeated_rankList_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserID_ = 0;
      for (int i = 0; i < rankList_.Count; i++) { MessagePool.Instance.Recycle(rankList_[i]); }
      rankList_.Clear();
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserID = input.ReadInt64();
            break;
          }
          case 18: {
            rankList_.AddEntriesFrom(input, _repeated_rankList_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///客户端不需要
  /// </summary>
  public partial class G2M_GetRankInfoRequest : pb::IMessage {
    private static readonly pb::MessageParser<G2M_GetRankInfoRequest> _parser = new pb::MessageParser<G2M_GetRankInfoRequest>(() => (G2M_GetRankInfoRequest)MessagePool.Instance.Fetch(typeof(G2M_GetRankInfoRequest)));
    public static pb::MessageParser<G2M_GetRankInfoRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int rankType_;
    public int RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RankType);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RankType);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rankType_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            RankType = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class M2G_GetRankInfoResponse : pb::IMessage {
    private static readonly pb::MessageParser<M2G_GetRankInfoResponse> _parser = new pb::MessageParser<M2G_GetRankInfoResponse>(() => (M2G_GetRankInfoResponse)MessagePool.Instance.Fetch(typeof(M2G_GetRankInfoResponse)));
    public static pb::MessageParser<M2G_GetRankInfoResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Rank_status> _repeated_rankList_codec
        = pb::FieldCodec.ForMessage(18, global::ETHotfix.Rank_status.Parser);
    private pbc::RepeatedField<global::ETHotfix.Rank_status> rankList_ = new pbc::RepeatedField<global::ETHotfix.Rank_status>();
    public pbc::RepeatedField<global::ETHotfix.Rank_status> RankList {
      get { return rankList_; }
      set { rankList_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      rankList_.WriteTo(output, _repeated_rankList_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      size += rankList_.CalculateSize(_repeated_rankList_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      for (int i = 0; i < rankList_.Count; i++) { MessagePool.Instance.Recycle(rankList_[i]); }
      rankList_.Clear();
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18: {
            rankList_.AddEntriesFrom(input, _repeated_rankList_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///触发排行
  /// </summary>
  public partial class G2M_EnterRankingRequest : pb::IMessage {
    private static readonly pb::MessageParser<G2M_EnterRankingRequest> _parser = new pb::MessageParser<G2M_EnterRankingRequest>(() => (G2M_EnterRankingRequest)MessagePool.Instance.Fetch(typeof(G2M_EnterRankingRequest)));
    public static pb::MessageParser<G2M_EnterRankingRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long value64A_;
    public long Value64A {
      get { return value64A_; }
      set {
        value64A_ = value;
      }
    }

    private long value64B_;
    public long Value64B {
      get { return value64B_; }
      set {
        value64B_ = value;
      }
    }

    private long value64C_;
    public long Value64C {
      get { return value64C_; }
      set {
        value64C_ = value;
      }
    }

    private int value32A_;
    public int Value32A {
      get { return value32A_; }
      set {
        value32A_ = value;
      }
    }

    private int value32B_;
    public int Value32B {
      get { return value32B_; }
      set {
        value32B_ = value;
      }
    }

    private int value32C_;
    public int Value32C {
      get { return value32C_; }
      set {
        value32C_ = value;
      }
    }

    private string strA_ = "";
    public string StrA {
      get { return strA_; }
      set {
        strA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string strB_ = "";
    public string StrB {
      get { return strB_; }
      set {
        strB_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string strC_ = "";
    public string StrC {
      get { return strC_; }
      set {
        strC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int rankType_;
    public int RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Value64A != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Value64A);
      }
      if (Value64B != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Value64B);
      }
      if (Value64C != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Value64C);
      }
      if (Value32A != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Value32A);
      }
      if (Value32B != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Value32B);
      }
      if (Value32C != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Value32C);
      }
      if (StrA.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StrA);
      }
      if (StrB.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(StrB);
      }
      if (StrC.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(StrC);
      }
      if (RankType != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(RankType);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (Value64A != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64A);
      }
      if (Value64B != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64B);
      }
      if (Value64C != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64C);
      }
      if (Value32A != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32A);
      }
      if (Value32B != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32B);
      }
      if (Value32C != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32C);
      }
      if (StrA.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrA);
      }
      if (StrB.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrB);
      }
      if (StrC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrC);
      }
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RankType);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      value64A_ = 0;
      value64B_ = 0;
      value64C_ = 0;
      value32A_ = 0;
      value32B_ = 0;
      value32C_ = 0;
      strA_ = "";
      strB_ = "";
      strC_ = "";
      rankType_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Value64A = input.ReadInt64();
            break;
          }
          case 16: {
            Value64B = input.ReadInt64();
            break;
          }
          case 24: {
            Value64C = input.ReadInt64();
            break;
          }
          case 32: {
            Value32A = input.ReadInt32();
            break;
          }
          case 40: {
            Value32B = input.ReadInt32();
            break;
          }
          case 48: {
            Value32C = input.ReadInt32();
            break;
          }
          case 58: {
            StrA = input.ReadString();
            break;
          }
          case 66: {
            StrB = input.ReadString();
            break;
          }
          case 74: {
            StrC = input.ReadString();
            break;
          }
          case 80: {
            RankType = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class M2G_EnterRankingResponse : pb::IMessage {
    private static readonly pb::MessageParser<M2G_EnterRankingResponse> _parser = new pb::MessageParser<M2G_EnterRankingResponse>(() => (M2G_EnterRankingResponse)MessagePool.Instance.Fetch(typeof(M2G_EnterRankingResponse)));
    public static pb::MessageParser<M2G_EnterRankingResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long endTime_;
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (EndTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(EndTime);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (EndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTime);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      endTime_ = 0;
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            EndTime = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///排行榜结算通知
  /// </summary>
  public partial class M2G_SettlementRankingMessage : pb::IMessage {
    private static readonly pb::MessageParser<M2G_SettlementRankingMessage> _parser = new pb::MessageParser<M2G_SettlementRankingMessage>(() => (M2G_SettlementRankingMessage)MessagePool.Instance.Fetch(typeof(M2G_SettlementRankingMessage)));
    public static pb::MessageParser<M2G_SettlementRankingMessage> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int rankType_;
    public int RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    private long value64A_;
    public long Value64A {
      get { return value64A_; }
      set {
        value64A_ = value;
      }
    }

    private long value64B_;
    public long Value64B {
      get { return value64B_; }
      set {
        value64B_ = value;
      }
    }

    private int value32A_;
    public int Value32A {
      get { return value32A_; }
      set {
        value32A_ = value;
      }
    }

    private int value32B_;
    public int Value32B {
      get { return value32B_; }
      set {
        value32B_ = value;
      }
    }

    private string strA_ = "";
    public string StrA {
      get { return strA_; }
      set {
        strA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string strB_ = "";
    public string StrB {
      get { return strB_; }
      set {
        strB_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RankType);
      }
      if (Value64A != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Value64A);
      }
      if (Value64B != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Value64B);
      }
      if (Value32A != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Value32A);
      }
      if (Value32B != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Value32B);
      }
      if (StrA.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(StrA);
      }
      if (StrB.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StrB);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RankType);
      }
      if (Value64A != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64A);
      }
      if (Value64B != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64B);
      }
      if (Value32A != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32A);
      }
      if (Value32B != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32B);
      }
      if (StrA.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrA);
      }
      if (StrB.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrB);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rankType_ = 0;
      value64A_ = 0;
      value64B_ = 0;
      value32A_ = 0;
      value32B_ = 0;
      strA_ = "";
      strB_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            RankType = input.ReadInt32();
            break;
          }
          case 16: {
            Value64A = input.ReadInt64();
            break;
          }
          case 24: {
            Value64B = input.ReadInt64();
            break;
          }
          case 32: {
            Value32A = input.ReadInt32();
            break;
          }
          case 40: {
            Value32B = input.ReadInt32();
            break;
          }
          case 50: {
            StrA = input.ReadString();
            break;
          }
          case 58: {
            StrB = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_SendFullServiceMessage : pb::IMessage {
    private static readonly pb::MessageParser<G2C_SendFullServiceMessage> _parser = new pb::MessageParser<G2C_SendFullServiceMessage>(() => (G2C_SendFullServiceMessage)MessagePool.Instance.Fetch(typeof(G2C_SendFullServiceMessage)));
    public static pb::MessageParser<G2C_SendFullServiceMessage> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private int titleID_;
    public int TitleID {
      get { return titleID_; }
      set {
        titleID_ = value;
      }
    }

    private int messageId_;
    public int MessageId {
      get { return messageId_; }
      set {
        messageId_ = value;
      }
    }

    private string playerName_ = "";
    public string PlayerName {
      get { return playerName_; }
      set {
        playerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TitleID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TitleID);
      }
      if (MessageId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MessageId);
      }
      if (PlayerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PlayerName);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (TitleID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TitleID);
      }
      if (MessageId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MessageId);
      }
      if (PlayerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerName);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      titleID_ = 0;
      messageId_ = 0;
      playerName_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TitleID = input.ReadInt32();
            break;
          }
          case 16: {
            MessageId = input.ReadInt32();
            break;
          }
          case 26: {
            PlayerName = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class Title_Status : pb::IMessage {
    private static readonly pb::MessageParser<Title_Status> _parser = new pb::MessageParser<Title_Status>(() => (Title_Status)MessagePool.Instance.Fetch(typeof(Title_Status)));
    public static pb::MessageParser<Title_Status> Parser { get { return _parser; } }

    private int titleID_;
    public int TitleID {
      get { return titleID_; }
      set {
        titleID_ = value;
      }
    }

    private long bingTime_;
    public long BingTime {
      get { return bingTime_; }
      set {
        bingTime_ = value;
      }
    }

    private long endTime_;
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TitleID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TitleID);
      }
      if (BingTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(BingTime);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(EndTime);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (TitleID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TitleID);
      }
      if (BingTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BingTime);
      }
      if (EndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTime);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      titleID_ = 0;
      bingTime_ = 0;
      endTime_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TitleID = input.ReadInt32();
            break;
          }
          case 16: {
            BingTime = input.ReadInt64();
            break;
          }
          case 24: {
            EndTime = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class Rank_status : pb::IMessage {
    private static readonly pb::MessageParser<Rank_status> _parser = new pb::MessageParser<Rank_status>(() => (Rank_status)MessagePool.Instance.Fetch(typeof(Rank_status)));
    public static pb::MessageParser<Rank_status> Parser { get { return _parser; } }

    private int rankType_;
    public int RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    private long value64A_;
    public long Value64A {
      get { return value64A_; }
      set {
        value64A_ = value;
      }
    }

    private long value64B_;
    public long Value64B {
      get { return value64B_; }
      set {
        value64B_ = value;
      }
    }

    private int value32A_;
    public int Value32A {
      get { return value32A_; }
      set {
        value32A_ = value;
      }
    }

    private int value32B_;
    public int Value32B {
      get { return value32B_; }
      set {
        value32B_ = value;
      }
    }

    private string strA_ = "";
    public string StrA {
      get { return strA_; }
      set {
        strA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string strB_ = "";
    public string StrB {
      get { return strB_; }
      set {
        strB_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RankType);
      }
      if (Value64A != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Value64A);
      }
      if (Value64B != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Value64B);
      }
      if (Value32A != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Value32A);
      }
      if (Value32B != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Value32B);
      }
      if (StrA.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(StrA);
      }
      if (StrB.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StrB);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RankType);
      }
      if (Value64A != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64A);
      }
      if (Value64B != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value64B);
      }
      if (Value32A != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32A);
      }
      if (Value32B != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value32B);
      }
      if (StrA.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrA);
      }
      if (StrB.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrB);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rankType_ = 0;
      value64A_ = 0;
      value64B_ = 0;
      value32A_ = 0;
      value32B_ = 0;
      strA_ = "";
      strB_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            RankType = input.ReadInt32();
            break;
          }
          case 16: {
            Value64A = input.ReadInt64();
            break;
          }
          case 24: {
            Value64B = input.ReadInt64();
            break;
          }
          case 32: {
            Value32A = input.ReadInt32();
            break;
          }
          case 40: {
            Value32B = input.ReadInt32();
            break;
          }
          case 50: {
            StrA = input.ReadString();
            break;
          }
          case 58: {
            StrB = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
