// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendSystemMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ETHotfix {

  #region Messages
  /// <summary>
  /// Opcode = 31000
  ///申请好友列表
  /// </summary>
  public partial class C2G_OpenFriendsinterfaceRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_OpenFriendsinterfaceRequest> _parser = new pb::MessageParser<C2G_OpenFriendsinterfaceRequest>(() => (C2G_OpenFriendsinterfaceRequest)MessagePool.Instance.Fetch(typeof(C2G_OpenFriendsinterfaceRequest)));
    public static pb::MessageParser<C2G_OpenFriendsinterfaceRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int listType_;
    public int ListType {
      get { return listType_; }
      set {
        listType_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ListType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ListType);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ListType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ListType);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      listType_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ListType = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///申请好友列表	返回
  /// </summary>
  public partial class G2C_OpenFriendsinterfaceResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_OpenFriendsinterfaceResponse> _parser = new pb::MessageParser<G2C_OpenFriendsinterfaceResponse>(() => (G2C_OpenFriendsinterfaceResponse)MessagePool.Instance.Fetch(typeof(G2C_OpenFriendsinterfaceResponse)));
    public static pb::MessageParser<G2C_OpenFriendsinterfaceResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_Friends> _repeated_fList_codec
        = pb::FieldCodec.ForMessage(10, global::ETHotfix.Struct_Friends.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_Friends> fList_ = new pbc::RepeatedField<global::ETHotfix.Struct_Friends>();
    public pbc::RepeatedField<global::ETHotfix.Struct_Friends> FList {
      get { return fList_; }
      set { fList_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      fList_.WriteTo(output, _repeated_fList_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      size += fList_.CalculateSize(_repeated_fList_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      for (int i = 0; i < fList_.Count; i++) { MessagePool.Instance.Recycle(fList_[i]); }
      fList_.Clear();
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            fList_.AddEntriesFrom(input, _repeated_fList_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///搜索好友
  /// </summary>
  public partial class C2G_SearchForFriendsRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_SearchForFriendsRequest> _parser = new pb::MessageParser<C2G_SearchForFriendsRequest>(() => (C2G_SearchForFriendsRequest)MessagePool.Instance.Fetch(typeof(C2G_SearchForFriendsRequest)));
    public static pb::MessageParser<C2G_SearchForFriendsRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private string charName_ = "";
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (CharName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CharName);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      charName_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            CharName = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///搜索好友	返回
  /// </summary>
  public partial class G2C_SearchForFriendsResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_SearchForFriendsResponse> _parser = new pb::MessageParser<G2C_SearchForFriendsResponse>(() => (G2C_SearchForFriendsResponse)MessagePool.Instance.Fetch(typeof(G2C_SearchForFriendsResponse)));
    public static pb::MessageParser<G2C_SearchForFriendsResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long gameUserId_;
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private string charName_ = "";
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int iState_;
    /// <summary>
    ///是否在线 0:在线	1:离线
    /// </summary>
    public int IState {
      get { return iState_; }
      set {
        iState_ = value;
      }
    }

    private int iLV_;
    public int ILV {
      get { return iLV_; }
      set {
        iLV_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (CharName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CharName);
      }
      if (IState != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IState);
      }
      if (ILV != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ILV);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      if (IState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IState);
      }
      if (ILV != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ILV);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      charName_ = "";
      iState_ = 0;
      iLV_ = 0;
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 18: {
            CharName = input.ReadString();
            break;
          }
          case 24: {
            IState = input.ReadInt32();
            break;
          }
          case 32: {
            ILV = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///添加好友
  /// </summary>
  public partial class C2G_AddFriendsRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_AddFriendsRequest> _parser = new pb::MessageParser<C2G_AddFriendsRequest>(() => (C2G_AddFriendsRequest)MessagePool.Instance.Fetch(typeof(C2G_AddFriendsRequest)));
    public static pb::MessageParser<C2G_AddFriendsRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long gameUserId_;
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private string charName_ = "";
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (CharName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CharName);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      charName_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 18: {
            CharName = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///添加好友 返回
  /// </summary>
  public partial class G2C_AddFriendsResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AddFriendsResponse> _parser = new pb::MessageParser<G2C_AddFriendsResponse>(() => (G2C_AddFriendsResponse)MessagePool.Instance.Fetch(typeof(G2C_AddFriendsResponse)));
    public static pb::MessageParser<G2C_AddFriendsResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///添加好友通知对方
  /// </summary>
  public partial class G2C_AddFriendsnotice_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AddFriendsnotice_notice> _parser = new pb::MessageParser<G2C_AddFriendsnotice_notice>(() => (G2C_AddFriendsnotice_notice)MessagePool.Instance.Fetch(typeof(G2C_AddFriendsnotice_notice)));
    public static pb::MessageParser<G2C_AddFriendsnotice_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private global::ETHotfix.Struct_Friends friendInfo_;
    public global::ETHotfix.Struct_Friends FriendInfo {
      get { return friendInfo_; }
      set {
        friendInfo_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (friendInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FriendInfo);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (friendInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FriendInfo);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      if (friendInfo_ != null) MessagePool.Instance.Recycle(friendInfo_); friendInfo_ = null;
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (friendInfo_ == null) {
              friendInfo_ = new global::ETHotfix.Struct_Friends();
            }
            input.ReadMessage(friendInfo_);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///同意或者拒绝 添加好友
  /// </summary>
  public partial class C2G_AgreeToAddFriendRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_AgreeToAddFriendRequest> _parser = new pb::MessageParser<C2G_AgreeToAddFriendRequest>(() => (C2G_AgreeToAddFriendRequest)MessagePool.Instance.Fetch(typeof(C2G_AgreeToAddFriendRequest)));
    public static pb::MessageParser<C2G_AgreeToAddFriendRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private int type_;
    /// <summary>
    ///Type=0 拒绝	Type=1 同意
    /// </summary>
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    private long gameUserId_;
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private string charName_ = "";
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Type);
      }
      if (GameUserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(GameUserId);
      }
      if (CharName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CharName);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      type_ = 0;
      gameUserId_ = 0;
      charName_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Type = input.ReadInt32();
            break;
          }
          case 16: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 26: {
            CharName = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///同意或者拒绝 添加好友返回
  /// </summary>
  public partial class G2C_AgreeToAddFriendResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AgreeToAddFriendResponse> _parser = new pb::MessageParser<G2C_AgreeToAddFriendResponse>(() => (G2C_AgreeToAddFriendResponse)MessagePool.Instance.Fetch(typeof(G2C_AgreeToAddFriendResponse)));
    public static pb::MessageParser<G2C_AgreeToAddFriendResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///同意或者拒绝 通知好友
  /// </summary>
  public partial class G2C_AgreeToAddFriend_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AgreeToAddFriend_notice> _parser = new pb::MessageParser<G2C_AgreeToAddFriend_notice>(() => (G2C_AgreeToAddFriend_notice)MessagePool.Instance.Fetch(typeof(G2C_AgreeToAddFriend_notice)));
    public static pb::MessageParser<G2C_AgreeToAddFriend_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private string charName_ = "";
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (CharName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CharName);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      charName_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            CharName = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class Struct_Friends : pb::IMessage {
    private static readonly pb::MessageParser<Struct_Friends> _parser = new pb::MessageParser<Struct_Friends>(() => (Struct_Friends)MessagePool.Instance.Fetch(typeof(Struct_Friends)));
    public static pb::MessageParser<Struct_Friends> Parser { get { return _parser; } }

    private long gameUserId_;
    /// <summary>
    ///ID
    /// </summary>
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private int listType_;
    /// <summary>
    ///类型(0:默认 1:拉黑 2:仇人 3:申请 4:好友)
    /// </summary>
    public int ListType {
      get { return listType_; }
      set {
        listType_ = value;
      }
    }

    private string charName_ = "";
    /// <summary>
    ///角色名
    /// </summary>
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int iState_;
    /// <summary>
    ///是否在线 0:在线	1:离线
    /// </summary>
    public int IState {
      get { return iState_; }
      set {
        iState_ = value;
      }
    }

    private int iLV_;
    public int ILV {
      get { return iLV_; }
      set {
        iLV_ = value;
      }
    }

    private long timeDate_;
    /// <summary>
    ///拉黑或者被击杀时间
    /// </summary>
    public long TimeDate {
      get { return timeDate_; }
      set {
        timeDate_ = value;
      }
    }

    private int classType_;
    /// <summary>
    ///职业类型
    /// </summary>
    public int ClassType {
      get { return classType_; }
      set {
        classType_ = value;
      }
    }

    private int warAlliancePost_;
    /// <summary>
    ///战盟职务
    /// </summary>
    public int WarAlliancePost {
      get { return warAlliancePost_; }
      set {
        warAlliancePost_ = value;
      }
    }

    private string warAllianceName_ = "";
    public string WarAllianceName {
      get { return warAllianceName_; }
      set {
        warAllianceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int occupationLevel_;
    /// <summary>
    ///专职次数
    /// </summary>
    public int OccupationLevel {
      get { return occupationLevel_; }
      set {
        occupationLevel_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (ListType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ListType);
      }
      if (CharName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CharName);
      }
      if (IState != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(IState);
      }
      if (ILV != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ILV);
      }
      if (TimeDate != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(TimeDate);
      }
      if (ClassType != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ClassType);
      }
      if (WarAlliancePost != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(WarAlliancePost);
      }
      if (WarAllianceName.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(WarAllianceName);
      }
      if (OccupationLevel != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(OccupationLevel);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (ListType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ListType);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      if (IState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IState);
      }
      if (ILV != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ILV);
      }
      if (TimeDate != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeDate);
      }
      if (ClassType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClassType);
      }
      if (WarAlliancePost != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WarAlliancePost);
      }
      if (WarAllianceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WarAllianceName);
      }
      if (OccupationLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OccupationLevel);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      listType_ = 0;
      charName_ = "";
      iState_ = 0;
      iLV_ = 0;
      timeDate_ = 0;
      classType_ = 0;
      warAlliancePost_ = 0;
      warAllianceName_ = "";
      occupationLevel_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 16: {
            ListType = input.ReadInt32();
            break;
          }
          case 26: {
            CharName = input.ReadString();
            break;
          }
          case 32: {
            IState = input.ReadInt32();
            break;
          }
          case 40: {
            ILV = input.ReadInt32();
            break;
          }
          case 48: {
            TimeDate = input.ReadInt64();
            break;
          }
          case 56: {
            ClassType = input.ReadInt32();
            break;
          }
          case 64: {
            WarAlliancePost = input.ReadInt32();
            break;
          }
          case 74: {
            WarAllianceName = input.ReadString();
            break;
          }
          case 80: {
            OccupationLevel = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///删除或者拉黑好友
  /// </summary>
  public partial class C2G_DeleteOrBlockFriendRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_DeleteOrBlockFriendRequest> _parser = new pb::MessageParser<C2G_DeleteOrBlockFriendRequest>(() => (C2G_DeleteOrBlockFriendRequest)MessagePool.Instance.Fetch(typeof(C2G_DeleteOrBlockFriendRequest)));
    public static pb::MessageParser<C2G_DeleteOrBlockFriendRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long gameUserId_;
    /// <summary>
    ///ID
    /// </summary>
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private int listType_;
    /// <summary>
    ///好友列表类型
    /// </summary>
    public int ListType {
      get { return listType_; }
      set {
        listType_ = value;
      }
    }

    private int type_;
    /// <summary>
    ///操作类型 0：删除好友  1；拉黑好友
    /// </summary>
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (ListType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ListType);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Type);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (ListType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ListType);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      listType_ = 0;
      type_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 16: {
            ListType = input.ReadInt32();
            break;
          }
          case 24: {
            Type = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///删除或者拉黑好友	返回
  /// </summary>
  public partial class G2C_DeleteOrBlockFriendResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_DeleteOrBlockFriendResponse> _parser = new pb::MessageParser<G2C_DeleteOrBlockFriendResponse>(() => (G2C_DeleteOrBlockFriendResponse)MessagePool.Instance.Fetch(typeof(G2C_DeleteOrBlockFriendResponse)));
    public static pb::MessageParser<G2C_DeleteOrBlockFriendResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///好友聊天
  /// </summary>
  public partial class C2G_FriendChatRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_FriendChatRequest> _parser = new pb::MessageParser<C2G_FriendChatRequest>(() => (C2G_FriendChatRequest)MessagePool.Instance.Fetch(typeof(C2G_FriendChatRequest)));
    public static pb::MessageParser<C2G_FriendChatRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long gameUserId_;
    /// <summary>
    ///ID
    /// </summary>
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private string iMessage_ = "";
    /// <summary>
    ///信息内容长度MAX50
    /// </summary>
    public string IMessage {
      get { return iMessage_; }
      set {
        iMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (IMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IMessage);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (IMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IMessage);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      iMessage_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 18: {
            IMessage = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///好友聊天 返回
  /// </summary>
  public partial class G2C_FriendChatResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_FriendChatResponse> _parser = new pb::MessageParser<G2C_FriendChatResponse>(() => (G2C_FriendChatResponse)MessagePool.Instance.Fetch(typeof(G2C_FriendChatResponse)));
    public static pb::MessageParser<G2C_FriendChatResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///好友聊天 通知
  /// </summary>
  public partial class G2C_FriendChat_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_FriendChat_notice> _parser = new pb::MessageParser<G2C_FriendChat_notice>(() => (G2C_FriendChat_notice)MessagePool.Instance.Fetch(typeof(G2C_FriendChat_notice)));
    public static pb::MessageParser<G2C_FriendChat_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private string iMessage_ = "";
    /// <summary>
    ///信息内容长度MAX50
    /// </summary>
    public string IMessage {
      get { return iMessage_; }
      set {
        iMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long gameUserId_;
    /// <summary>
    ///角色ID
    /// </summary>
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private long dateTiem_;
    /// <summary>
    ///发送时间
    /// </summary>
    public long DateTiem {
      get { return dateTiem_; }
      set {
        dateTiem_ = value;
      }
    }

    private string charName_ = "";
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (IMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IMessage);
      }
      if (GameUserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(GameUserId);
      }
      if (DateTiem != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(DateTiem);
      }
      if (CharName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CharName);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (IMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IMessage);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (DateTiem != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DateTiem);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      iMessage_ = "";
      gameUserId_ = 0;
      dateTiem_ = 0;
      charName_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            IMessage = input.ReadString();
            break;
          }
          case 16: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 24: {
            DateTiem = input.ReadInt64();
            break;
          }
          case 34: {
            CharName = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///好友传送
  /// </summary>
  public partial class C2G_FriendDeliveryRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_FriendDeliveryRequest> _parser = new pb::MessageParser<C2G_FriendDeliveryRequest>(() => (C2G_FriendDeliveryRequest)MessagePool.Instance.Fetch(typeof(C2G_FriendDeliveryRequest)));
    public static pb::MessageParser<C2G_FriendDeliveryRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long gameUserId_;
    /// <summary>
    ///ID
    /// </summary>
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///好友传送 返回
  /// </summary>
  public partial class G2C_FriendDeliveryResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_FriendDeliveryResponse> _parser = new pb::MessageParser<G2C_FriendDeliveryResponse>(() => (G2C_FriendDeliveryResponse)MessagePool.Instance.Fetch(typeof(G2C_FriendDeliveryResponse)));
    public static pb::MessageParser<G2C_FriendDeliveryResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///好友推荐
  /// </summary>
  public partial class C2G_FriendRecommendRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_FriendRecommendRequest> _parser = new pb::MessageParser<C2G_FriendRecommendRequest>(() => (C2G_FriendRecommendRequest)MessagePool.Instance.Fetch(typeof(C2G_FriendRecommendRequest)));
    public static pb::MessageParser<C2G_FriendRecommendRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///好友推荐 返回
  /// </summary>
  public partial class G2C_FriendRecommendResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_FriendRecommendResponse> _parser = new pb::MessageParser<G2C_FriendRecommendResponse>(() => (G2C_FriendRecommendResponse)MessagePool.Instance.Fetch(typeof(G2C_FriendRecommendResponse)));
    public static pb::MessageParser<G2C_FriendRecommendResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_Friends> _repeated_fList_codec
        = pb::FieldCodec.ForMessage(10, global::ETHotfix.Struct_Friends.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_Friends> fList_ = new pbc::RepeatedField<global::ETHotfix.Struct_Friends>();
    /// <summary>
    ///返回长度十个
    /// </summary>
    public pbc::RepeatedField<global::ETHotfix.Struct_Friends> FList {
      get { return fList_; }
      set { fList_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      fList_.WriteTo(output, _repeated_fList_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      size += fList_.CalculateSize(_repeated_fList_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      for (int i = 0; i < fList_.Count; i++) { MessagePool.Instance.Recycle(fList_[i]); }
      fList_.Clear();
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            fList_.AddEntriesFrom(input, _repeated_fList_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///获取位置信息
  /// </summary>
  public partial class C2G_FriendPositionRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_FriendPositionRequest> _parser = new pb::MessageParser<C2G_FriendPositionRequest>(() => (C2G_FriendPositionRequest)MessagePool.Instance.Fetch(typeof(C2G_FriendPositionRequest)));
    public static pb::MessageParser<C2G_FriendPositionRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long gameUserId_;
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///获取位置信息 返回
  /// </summary>
  public partial class G2C_FriendPositionResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_FriendPositionResponse> _parser = new pb::MessageParser<G2C_FriendPositionResponse>(() => (G2C_FriendPositionResponse)MessagePool.Instance.Fetch(typeof(G2C_FriendPositionResponse)));
    public static pb::MessageParser<G2C_FriendPositionResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///获取位置信息 通知
  /// </summary>
  public partial class G2C_FriendPositionMessage : pb::IMessage {
    private static readonly pb::MessageParser<G2C_FriendPositionMessage> _parser = new pb::MessageParser<G2C_FriendPositionMessage>(() => (G2C_FriendPositionMessage)MessagePool.Instance.Fetch(typeof(G2C_FriendPositionMessage)));
    public static pb::MessageParser<G2C_FriendPositionMessage> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private int x_;
    /// <summary>
    ///坐标
    /// </summary>
    public int X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    private int y_;
    public int Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    private int mapID_;
    /// <summary>
    ///地图ID
    /// </summary>
    public int MapID {
      get { return mapID_; }
      set {
        mapID_ = value;
      }
    }

    private long gameUserId_;
    /// <summary>
    ///发送者ID
    /// </summary>
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private long dateTime_;
    public long DateTime {
      get { return dateTime_; }
      set {
        dateTime_ = value;
      }
    }

    private string charName_ = "";
    public string CharName {
      get { return charName_; }
      set {
        charName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Y);
      }
      if (MapID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MapID);
      }
      if (GameUserId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(GameUserId);
      }
      if (DateTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(DateTime);
      }
      if (CharName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CharName);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
      }
      if (MapID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MapID);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (DateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DateTime);
      }
      if (CharName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharName);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      x_ = 0;
      y_ = 0;
      mapID_ = 0;
      gameUserId_ = 0;
      dateTime_ = 0;
      charName_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            X = input.ReadInt32();
            break;
          }
          case 16: {
            Y = input.ReadInt32();
            break;
          }
          case 24: {
            MapID = input.ReadInt32();
            break;
          }
          case 32: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 40: {
            DateTime = input.ReadInt64();
            break;
          }
          case 50: {
            CharName = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
