// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotfixWarehouseMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ETHotfix {

  #region Messages
  /// <summary>
  /// Opcode = 28000
  ///=========================仓库============================
  /// 移动仓库物品的位置 推送G2C_MoveWarehouseItem_notice 
  /// </summary>
  public partial class C2G_MoveWarehouseItem : pb::IMessage {
    private static readonly pb::MessageParser<C2G_MoveWarehouseItem> _parser = new pb::MessageParser<C2G_MoveWarehouseItem>(() => (C2G_MoveWarehouseItem)MessagePool.Instance.Fetch(typeof(C2G_MoveWarehouseItem)));
    public static pb::MessageParser<C2G_MoveWarehouseItem> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long itemUUID_;
    public long ItemUUID {
      get { return itemUUID_; }
      set {
        itemUUID_ = value;
      }
    }

    private int posInBackpackX_;
    public int PosInBackpackX {
      get { return posInBackpackX_; }
      set {
        posInBackpackX_ = value;
      }
    }

    private int posInBackpackY_;
    public int PosInBackpackY {
      get { return posInBackpackY_; }
      set {
        posInBackpackY_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemUUID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ItemUUID);
      }
      if (PosInBackpackX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PosInBackpackX);
      }
      if (PosInBackpackY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PosInBackpackY);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ItemUUID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemUUID);
      }
      if (PosInBackpackX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosInBackpackX);
      }
      if (PosInBackpackY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosInBackpackY);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      itemUUID_ = 0;
      posInBackpackX_ = 0;
      posInBackpackY_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 16: {
            ItemUUID = input.ReadInt64();
            break;
          }
          case 24: {
            PosInBackpackX = input.ReadInt32();
            break;
          }
          case 32: {
            PosInBackpackY = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 移动仓库物品的位置  返回 
  /// </summary>
  public partial class G2C_MoveWarehouseItem : pb::IMessage {
    private static readonly pb::MessageParser<G2C_MoveWarehouseItem> _parser = new pb::MessageParser<G2C_MoveWarehouseItem>(() => (G2C_MoveWarehouseItem)MessagePool.Instance.Fetch(typeof(G2C_MoveWarehouseItem)));
    public static pb::MessageParser<G2C_MoveWarehouseItem> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 从背包添加到仓库  推送G2C_AddWarehouseItem_notice 
  /// </summary>
  public partial class C2G_AddWarehouseItem : pb::IMessage {
    private static readonly pb::MessageParser<C2G_AddWarehouseItem> _parser = new pb::MessageParser<C2G_AddWarehouseItem>(() => (C2G_AddWarehouseItem)MessagePool.Instance.Fetch(typeof(C2G_AddWarehouseItem)));
    public static pb::MessageParser<C2G_AddWarehouseItem> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long itemUUID_;
    public long ItemUUID {
      get { return itemUUID_; }
      set {
        itemUUID_ = value;
      }
    }

    private int posInBackpackX_;
    public int PosInBackpackX {
      get { return posInBackpackX_; }
      set {
        posInBackpackX_ = value;
      }
    }

    private int posInBackpackY_;
    public int PosInBackpackY {
      get { return posInBackpackY_; }
      set {
        posInBackpackY_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemUUID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ItemUUID);
      }
      if (PosInBackpackX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PosInBackpackX);
      }
      if (PosInBackpackY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PosInBackpackY);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ItemUUID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemUUID);
      }
      if (PosInBackpackX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosInBackpackX);
      }
      if (PosInBackpackY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosInBackpackY);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      itemUUID_ = 0;
      posInBackpackX_ = 0;
      posInBackpackY_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 16: {
            ItemUUID = input.ReadInt64();
            break;
          }
          case 24: {
            PosInBackpackX = input.ReadInt32();
            break;
          }
          case 32: {
            PosInBackpackY = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 从背包添加到仓库  返回 
  /// </summary>
  public partial class G2C_AddWarehouseItem : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AddWarehouseItem> _parser = new pb::MessageParser<G2C_AddWarehouseItem>(() => (G2C_AddWarehouseItem)MessagePool.Instance.Fetch(typeof(G2C_AddWarehouseItem)));
    public static pb::MessageParser<G2C_AddWarehouseItem> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 仓库物品移动到背包  推送G2C_ItemsLeaveBackpack_notice
  /// </summary>
  public partial class C2G_DelWarehouseItem : pb::IMessage {
    private static readonly pb::MessageParser<C2G_DelWarehouseItem> _parser = new pb::MessageParser<C2G_DelWarehouseItem>(() => (C2G_DelWarehouseItem)MessagePool.Instance.Fetch(typeof(C2G_DelWarehouseItem)));
    public static pb::MessageParser<C2G_DelWarehouseItem> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long itemUUID_;
    public long ItemUUID {
      get { return itemUUID_; }
      set {
        itemUUID_ = value;
      }
    }

    private int posInBackpackX_;
    public int PosInBackpackX {
      get { return posInBackpackX_; }
      set {
        posInBackpackX_ = value;
      }
    }

    private int posInBackpackY_;
    public int PosInBackpackY {
      get { return posInBackpackY_; }
      set {
        posInBackpackY_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemUUID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ItemUUID);
      }
      if (PosInBackpackX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PosInBackpackX);
      }
      if (PosInBackpackY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PosInBackpackY);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (ItemUUID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemUUID);
      }
      if (PosInBackpackX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosInBackpackX);
      }
      if (PosInBackpackY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosInBackpackY);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      itemUUID_ = 0;
      posInBackpackX_ = 0;
      posInBackpackY_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ItemUUID = input.ReadInt64();
            break;
          }
          case 24: {
            PosInBackpackX = input.ReadInt32();
            break;
          }
          case 32: {
            PosInBackpackY = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 仓库物品移动到背包  返回
  /// </summary>
  public partial class G2C_DelWarehouseItem : pb::IMessage {
    private static readonly pb::MessageParser<G2C_DelWarehouseItem> _parser = new pb::MessageParser<G2C_DelWarehouseItem>(() => (G2C_DelWarehouseItem)MessagePool.Instance.Fetch(typeof(G2C_DelWarehouseItem)));
    public static pb::MessageParser<G2C_DelWarehouseItem> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 放进金币到仓库  推送G2C_BackpackGoldChange_notice和G2C_WarehouseGoldChange_notice
  /// </summary>
  public partial class C2G_AddGoldToWarehouse : pb::IMessage {
    private static readonly pb::MessageParser<C2G_AddGoldToWarehouse> _parser = new pb::MessageParser<C2G_AddGoldToWarehouse>(() => (C2G_AddGoldToWarehouse)MessagePool.Instance.Fetch(typeof(C2G_AddGoldToWarehouse)));
    public static pb::MessageParser<C2G_AddGoldToWarehouse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long gold_;
    public long Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Gold != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Gold);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (Gold != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Gold);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gold_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Gold = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 放进金币到仓库  返回
  /// </summary>
  public partial class G2C_AddGoldToWarehouse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AddGoldToWarehouse> _parser = new pb::MessageParser<G2C_AddGoldToWarehouse>(() => (G2C_AddGoldToWarehouse)MessagePool.Instance.Fetch(typeof(G2C_AddGoldToWarehouse)));
    public static pb::MessageParser<G2C_AddGoldToWarehouse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 从仓库中取出金币  推送G2C_BackpackGoldChange_notice和G2C_WarehouseGoldChange_notice
  /// </summary>
  public partial class C2G_TackOutGoldInWarehouse : pb::IMessage {
    private static readonly pb::MessageParser<C2G_TackOutGoldInWarehouse> _parser = new pb::MessageParser<C2G_TackOutGoldInWarehouse>(() => (C2G_TackOutGoldInWarehouse)MessagePool.Instance.Fetch(typeof(C2G_TackOutGoldInWarehouse)));
    public static pb::MessageParser<C2G_TackOutGoldInWarehouse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long gold_;
    public long Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Gold != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Gold);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (Gold != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Gold);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gold_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Gold = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 从仓库中取出金币  返回
  /// </summary>
  public partial class G2C_TackOutGoldInWarehouse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_TackOutGoldInWarehouse> _parser = new pb::MessageParser<G2C_TackOutGoldInWarehouse>(() => (G2C_TackOutGoldInWarehouse)MessagePool.Instance.Fetch(typeof(G2C_TackOutGoldInWarehouse)));
    public static pb::MessageParser<G2C_TackOutGoldInWarehouse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///============================推送==============================
  ///推送客户端仓库中有物品进入 选择角色进入游戏场景时会推送玩家仓库里现有物品
  /// </summary>
  public partial class G2C_AddWarehouseItem_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_AddWarehouseItem_notice> _parser = new pb::MessageParser<G2C_AddWarehouseItem_notice>(() => (G2C_AddWarehouseItem_notice)MessagePool.Instance.Fetch(typeof(G2C_AddWarehouseItem_notice)));
    public static pb::MessageParser<G2C_AddWarehouseItem_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Struct_ItemInBackpack_Status> _repeated_allItems_codec
        = pb::FieldCodec.ForMessage(10, global::ETHotfix.Struct_ItemInBackpack_Status.Parser);
    private pbc::RepeatedField<global::ETHotfix.Struct_ItemInBackpack_Status> allItems_ = new pbc::RepeatedField<global::ETHotfix.Struct_ItemInBackpack_Status>();
    public pbc::RepeatedField<global::ETHotfix.Struct_ItemInBackpack_Status> AllItems {
      get { return allItems_; }
      set { allItems_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      allItems_.WriteTo(output, _repeated_allItems_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      size += allItems_.CalculateSize(_repeated_allItems_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      for (int i = 0; i < allItems_.Count; i++) { MessagePool.Instance.Recycle(allItems_[i]); }
      allItems_.Clear();
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            allItems_.AddEntriesFrom(input, _repeated_allItems_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///推送客户端仓库中有物品离开
  /// </summary>
  public partial class G2C_DelWarehouseItem_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_DelWarehouseItem_notice> _parser = new pb::MessageParser<G2C_DelWarehouseItem_notice>(() => (G2C_DelWarehouseItem_notice)MessagePool.Instance.Fetch(typeof(G2C_DelWarehouseItem_notice)));
    public static pb::MessageParser<G2C_DelWarehouseItem_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long gameUserId_;
    /// <summary>
    /// 实体玩家的仓库
    /// </summary>
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private long leaveItemUUID_;
    /// <summary>
    /// 离开仓库的物品UUID
    /// </summary>
    public long LeaveItemUUID {
      get { return leaveItemUUID_; }
      set {
        leaveItemUUID_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (LeaveItemUUID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LeaveItemUUID);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (LeaveItemUUID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LeaveItemUUID);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      leaveItemUUID_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 16: {
            LeaveItemUUID = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///推送客户端仓库中有物品位置变动
  /// </summary>
  public partial class G2C_MoveWarehouseItem_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_MoveWarehouseItem_notice> _parser = new pb::MessageParser<G2C_MoveWarehouseItem_notice>(() => (G2C_MoveWarehouseItem_notice)MessagePool.Instance.Fetch(typeof(G2C_MoveWarehouseItem_notice)));
    public static pb::MessageParser<G2C_MoveWarehouseItem_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long gameUserId_;
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private long itemUUID_;
    public long ItemUUID {
      get { return itemUUID_; }
      set {
        itemUUID_ = value;
      }
    }

    private int posInBackpackX_;
    public int PosInBackpackX {
      get { return posInBackpackX_; }
      set {
        posInBackpackX_ = value;
      }
    }

    private int posInBackpackY_;
    public int PosInBackpackY {
      get { return posInBackpackY_; }
      set {
        posInBackpackY_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (ItemUUID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ItemUUID);
      }
      if (PosInBackpackX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PosInBackpackX);
      }
      if (PosInBackpackY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PosInBackpackY);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (ItemUUID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemUUID);
      }
      if (PosInBackpackX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosInBackpackX);
      }
      if (PosInBackpackY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosInBackpackY);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      itemUUID_ = 0;
      posInBackpackX_ = 0;
      posInBackpackY_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 16: {
            ItemUUID = input.ReadInt64();
            break;
          }
          case 24: {
            PosInBackpackX = input.ReadInt32();
            break;
          }
          case 32: {
            PosInBackpackY = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///推送仓库扩建
  /// </summary>
  public partial class G2C_WarehouseExtension_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_WarehouseExtension_notice> _parser = new pb::MessageParser<G2C_WarehouseExtension_notice>(() => (G2C_WarehouseExtension_notice)MessagePool.Instance.Fetch(typeof(G2C_WarehouseExtension_notice)));
    public static pb::MessageParser<G2C_WarehouseExtension_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private int capacity_;
    public int Capacity {
      get { return capacity_; }
      set {
        capacity_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Capacity != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Capacity);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (Capacity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Capacity);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      capacity_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Capacity = input.ReadInt32();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///广播玩家背包金币数值变动  选择角色进入游戏场景时或者金币变动时会推送
  /// </summary>
  public partial class G2C_WarehouseGoldChange_notice : pb::IMessage {
    private static readonly pb::MessageParser<G2C_WarehouseGoldChange_notice> _parser = new pb::MessageParser<G2C_WarehouseGoldChange_notice>(() => (G2C_WarehouseGoldChange_notice)MessagePool.Instance.Fetch(typeof(G2C_WarehouseGoldChange_notice)));
    public static pb::MessageParser<G2C_WarehouseGoldChange_notice> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long gameUserId_;
    public long GameUserId {
      get { return gameUserId_; }
      set {
        gameUserId_ = value;
      }
    }

    private long gold_;
    public long Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (GameUserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(GameUserId);
      }
      if (Gold != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Gold);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (GameUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameUserId);
      }
      if (Gold != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Gold);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      gameUserId_ = 0;
      gold_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GameUserId = input.ReadInt64();
            break;
          }
          case 16: {
            Gold = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
