// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotfxMailMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ETHotfix {

  #region Messages
  /// <summary>
  /// Opcode = 37000
  ///新邮件通知
  /// </summary>
  public partial class G2C_ServerSendMailMessage : pb::IMessage {
    private static readonly pb::MessageParser<G2C_ServerSendMailMessage> _parser = new pb::MessageParser<G2C_ServerSendMailMessage>(() => (G2C_ServerSendMailMessage)MessagePool.Instance.Fetch(typeof(G2C_ServerSendMailMessage)));
    public static pb::MessageParser<G2C_ServerSendMailMessage> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///点击确认以读取
  /// </summary>
  public partial class C2G_ReadMailRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_ReadMailRequest> _parser = new pb::MessageParser<C2G_ReadMailRequest>(() => (C2G_ReadMailRequest)MessagePool.Instance.Fetch(typeof(C2G_ReadMailRequest)));
    public static pb::MessageParser<C2G_ReadMailRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private long mailId_;
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (MailId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MailId);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      mailId_ = 0;
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MailId = input.ReadInt64();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_ReadMailResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_ReadMailResponse> _parser = new pb::MessageParser<G2C_ReadMailResponse>(() => (G2C_ReadMailResponse)MessagePool.Instance.Fetch(typeof(G2C_ReadMailResponse)));
    public static pb::MessageParser<G2C_ReadMailResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///领取道具
  /// </summary>
  public partial class C2G_MailReceiveItemRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_MailReceiveItemRequest> _parser = new pb::MessageParser<C2G_MailReceiveItemRequest>(() => (C2G_MailReceiveItemRequest)MessagePool.Instance.Fetch(typeof(C2G_MailReceiveItemRequest)));
    public static pb::MessageParser<C2G_MailReceiveItemRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private static readonly pb::FieldCodec<long> _repeated_mailId_codec
        = pb::FieldCodec.ForInt64(10);
    private pbc::RepeatedField<long> mailId_ = new pbc::RepeatedField<long>();
    public pbc::RepeatedField<long> MailId {
      get { return mailId_; }
      set { mailId_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      mailId_.WriteTo(output, _repeated_mailId_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      size += mailId_.CalculateSize(_repeated_mailId_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      mailId_.Clear();
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            mailId_.AddEntriesFrom(input, _repeated_mailId_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_MailReceiveItemResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_MailReceiveItemResponse> _parser = new pb::MessageParser<G2C_MailReceiveItemResponse>(() => (G2C_MailReceiveItemResponse)MessagePool.Instance.Fetch(typeof(G2C_MailReceiveItemResponse)));
    public static pb::MessageParser<G2C_MailReceiveItemResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///删除邮件
  /// </summary>
  public partial class C2G_MailDeleteItemRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_MailDeleteItemRequest> _parser = new pb::MessageParser<C2G_MailDeleteItemRequest>(() => (C2G_MailDeleteItemRequest)MessagePool.Instance.Fetch(typeof(C2G_MailDeleteItemRequest)));
    public static pb::MessageParser<C2G_MailDeleteItemRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    private static readonly pb::FieldCodec<long> _repeated_mailId_codec
        = pb::FieldCodec.ForInt64(10);
    private pbc::RepeatedField<long> mailId_ = new pbc::RepeatedField<long>();
    public pbc::RepeatedField<long> MailId {
      get { return mailId_; }
      set { mailId_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      mailId_.WriteTo(output, _repeated_mailId_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      size += mailId_.CalculateSize(_repeated_mailId_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      mailId_.Clear();
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            mailId_.AddEntriesFrom(input, _repeated_mailId_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_MailDeleteItemResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_MailDeleteItemResponse> _parser = new pb::MessageParser<G2C_MailDeleteItemResponse>(() => (G2C_MailDeleteItemResponse)MessagePool.Instance.Fetch(typeof(G2C_MailDeleteItemResponse)));
    public static pb::MessageParser<G2C_MailDeleteItemResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///打开邮件
  /// </summary>
  public partial class C2G_OpenMailRequest : pb::IMessage {
    private static readonly pb::MessageParser<C2G_OpenMailRequest> _parser = new pb::MessageParser<C2G_OpenMailRequest>(() => (C2G_OpenMailRequest)MessagePool.Instance.Fetch(typeof(C2G_OpenMailRequest)));
    public static pb::MessageParser<C2G_OpenMailRequest> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private long appendData_;
    public long AppendData {
      get { return appendData_; }
      set {
        appendData_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
      if (AppendData != 0L) {
        output.WriteRawTag(224, 5);
        output.WriteInt64(AppendData);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (AppendData != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(AppendData);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      appendData_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
          case 736: {
            AppendData = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_OpenMailResponse : pb::IMessage {
    private static readonly pb::MessageParser<G2C_OpenMailResponse> _parser = new pb::MessageParser<G2C_OpenMailResponse>(() => (G2C_OpenMailResponse)MessagePool.Instance.Fetch(typeof(G2C_OpenMailResponse)));
    public static pb::MessageParser<G2C_OpenMailResponse> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private int error_;
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Mailinfo> _repeated_mailList_codec
        = pb::FieldCodec.ForMessage(10, global::ETHotfix.Mailinfo.Parser);
    private pbc::RepeatedField<global::ETHotfix.Mailinfo> mailList_ = new pbc::RepeatedField<global::ETHotfix.Mailinfo>();
    public pbc::RepeatedField<global::ETHotfix.Mailinfo> MailList {
      get { return mailList_; }
      set { mailList_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      mailList_.WriteTo(output, _repeated_mailList_codec);
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (Error != 0) {
        output.WriteRawTag(216, 5);
        output.WriteInt32(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(226, 5);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (Error != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (Message.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      size += mailList_.CalculateSize(_repeated_mailList_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      for (int i = 0; i < mailList_.Count; i++) { MessagePool.Instance.Recycle(mailList_[i]); }
      mailList_.Clear();
      rpcId_ = 0;
      error_ = 0;
      message_ = "";
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            mailList_.AddEntriesFrom(input, _repeated_mailList_codec);
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            Error = input.ReadInt32();
            break;
          }
          case 738: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public partial class G2G_SendFullServiceMailMessage : pb::IMessage {
    private static readonly pb::MessageParser<G2G_SendFullServiceMailMessage> _parser = new pb::MessageParser<G2G_SendFullServiceMailMessage>(() => (G2G_SendFullServiceMailMessage)MessagePool.Instance.Fetch(typeof(G2G_SendFullServiceMailMessage)));
    public static pb::MessageParser<G2G_SendFullServiceMailMessage> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    private int zoneId_;
    public int ZoneId {
      get { return zoneId_; }
      set {
        zoneId_ = value;
      }
    }

    private string name_ = "";
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string content_ = "";
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string mailItems_ = "";
    public string MailItems {
      get { return mailItems_; }
      set {
        mailItems_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ZoneId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ZoneId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Content);
      }
      if (MailItems.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MailItems);
      }
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (ZoneId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ZoneId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (MailItems.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailItems);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      zoneId_ = 0;
      name_ = "";
      content_ = "";
      mailItems_ = "";
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ZoneId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Content = input.ReadString();
            break;
          }
          case 34: {
            MailItems = input.ReadString();
            break;
          }
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class G2C_LoadMaillUnreadMessage : pb::IMessage {
    private static readonly pb::MessageParser<G2C_LoadMaillUnreadMessage> _parser = new pb::MessageParser<G2C_LoadMaillUnreadMessage>(() => (G2C_LoadMaillUnreadMessage)MessagePool.Instance.Fetch(typeof(G2C_LoadMaillUnreadMessage)));
    public static pb::MessageParser<G2C_LoadMaillUnreadMessage> Parser { get { return _parser; } }

    private int rpcId_;
    public int RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    private long actorId_;
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (RpcId != 0) {
        output.WriteRawTag(208, 5);
        output.WriteInt32(RpcId);
      }
      if (ActorId != 0L) {
        output.WriteRawTag(216, 5);
        output.WriteInt64(ActorId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (RpcId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RpcId);
      }
      if (ActorId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      rpcId_ = 0;
      actorId_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 720: {
            RpcId = input.ReadInt32();
            break;
          }
          case 728: {
            ActorId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public partial class Mailinfo : pb::IMessage {
    private static readonly pb::MessageParser<Mailinfo> _parser = new pb::MessageParser<Mailinfo>(() => (Mailinfo)MessagePool.Instance.Fetch(typeof(Mailinfo)));
    public static pb::MessageParser<Mailinfo> Parser { get { return _parser; } }

    private long mailId_;
    /// <summary>
    ///邮件ID
    /// </summary>
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    private string mailName_ = "";
    /// <summary>
    ///邮件名称
    /// </summary>
    public string MailName {
      get { return mailName_; }
      set {
        mailName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private long mailAcceptanceTime_;
    /// <summary>
    ///接收时间秒
    /// </summary>
    public long MailAcceptanceTime {
      get { return mailAcceptanceTime_; }
      set {
        mailAcceptanceTime_ = value;
      }
    }

    private long mailValidTime_;
    /// <summary>
    ///有效时长 = 接收时间 + 15天
    /// </summary>
    public long MailValidTime {
      get { return mailValidTime_; }
      set {
        mailValidTime_ = value;
      }
    }

    private string mailContent_ = "";
    /// <summary>
    ///邮件内容
    /// </summary>
    public string MailContent {
      get { return mailContent_; }
      set {
        mailContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int mailState_;
    /// <summary>
    ///邮件状态 0未读 1已读
    /// </summary>
    public int MailState {
      get { return mailState_; }
      set {
        mailState_ = value;
      }
    }

    private int receiveOrNot_;
    /// <summary>
    ///附件是否领取
    /// </summary>
    public int ReceiveOrNot {
      get { return receiveOrNot_; }
      set {
        receiveOrNot_ = value;
      }
    }

    private static readonly pb::FieldCodec<global::ETHotfix.Iteminfo> _repeated_mailEnclosure_codec
        = pb::FieldCodec.ForMessage(66, global::ETHotfix.Iteminfo.Parser);
    private pbc::RepeatedField<global::ETHotfix.Iteminfo> mailEnclosure_ = new pbc::RepeatedField<global::ETHotfix.Iteminfo>();
    /// <summary>
    ///附件
    /// </summary>
    public pbc::RepeatedField<global::ETHotfix.Iteminfo> MailEnclosure {
      get { return mailEnclosure_; }
      set { mailEnclosure_ = value; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (MailId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MailId);
      }
      if (MailName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MailName);
      }
      if (MailAcceptanceTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MailAcceptanceTime);
      }
      if (MailValidTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(MailValidTime);
      }
      if (MailContent.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MailContent);
      }
      if (MailState != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MailState);
      }
      if (ReceiveOrNot != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ReceiveOrNot);
      }
      mailEnclosure_.WriteTo(output, _repeated_mailEnclosure_codec);
    }

    public int CalculateSize() {
      int size = 0;
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      if (MailName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailName);
      }
      if (MailAcceptanceTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailAcceptanceTime);
      }
      if (MailValidTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailValidTime);
      }
      if (MailContent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailContent);
      }
      if (MailState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MailState);
      }
      if (ReceiveOrNot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReceiveOrNot);
      }
      size += mailEnclosure_.CalculateSize(_repeated_mailEnclosure_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      mailId_ = 0;
      mailName_ = "";
      mailAcceptanceTime_ = 0;
      mailValidTime_ = 0;
      mailContent_ = "";
      mailState_ = 0;
      receiveOrNot_ = 0;
      for (int i = 0; i < mailEnclosure_.Count; i++) { MessagePool.Instance.Recycle(mailEnclosure_[i]); }
      mailEnclosure_.Clear();
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MailId = input.ReadInt64();
            break;
          }
          case 18: {
            MailName = input.ReadString();
            break;
          }
          case 24: {
            MailAcceptanceTime = input.ReadInt64();
            break;
          }
          case 32: {
            MailValidTime = input.ReadInt64();
            break;
          }
          case 42: {
            MailContent = input.ReadString();
            break;
          }
          case 48: {
            MailState = input.ReadInt32();
            break;
          }
          case 56: {
            ReceiveOrNot = input.ReadInt32();
            break;
          }
          case 66: {
            mailEnclosure_.AddEntriesFrom(input, _repeated_mailEnclosure_codec);
            break;
          }
        }
      }
    }

  }

  public partial class Iteminfo : pb::IMessage {
    private static readonly pb::MessageParser<Iteminfo> _parser = new pb::MessageParser<Iteminfo>(() => (Iteminfo)MessagePool.Instance.Fetch(typeof(Iteminfo)));
    public static pb::MessageParser<Iteminfo> Parser { get { return _parser; } }

    private int itemConfigID_;
    /// <summary>
    ///道具配置ID
    /// </summary>
    public int ItemConfigID {
      get { return itemConfigID_; }
      set {
        itemConfigID_ = value;
      }
    }

    private long itemID_;
    /// <summary>
    ///道具唯一ID，没有是0
    /// </summary>
    public long ItemID {
      get { return itemID_; }
      set {
        itemID_ = value;
      }
    }

    private int itemCnt_;
    /// <summary>
    ///道具数量
    /// </summary>
    public int ItemCnt {
      get { return itemCnt_; }
      set {
        itemCnt_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemConfigID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemConfigID);
      }
      if (ItemID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ItemID);
      }
      if (ItemCnt != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ItemCnt);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (ItemConfigID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemConfigID);
      }
      if (ItemID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemID);
      }
      if (ItemCnt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemCnt);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      itemConfigID_ = 0;
      itemID_ = 0;
      itemCnt_ = 0;
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ItemConfigID = input.ReadInt32();
            break;
          }
          case 16: {
            ItemID = input.ReadInt64();
            break;
          }
          case 24: {
            ItemCnt = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
